### ISSUE TITLE
Locust shows an exception when running after sending the request successfully

### ISSUE THREAD

**Issue by Preyansh91** [locustio/locust#1094]
Following is the error being seen:
```
JCMAC115JHD4/INFO/stdout: 
[2019-09-26 17:37:32,421] SJCMAC115JHD4/ERROR/stderr: /Users/preshah/redlock-auto/venv3.7/lib/python3.7/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[2019-09-26 17:37:32,649] SJCMAC115JHD4/ERROR/stderr: Traceback (most recent call last):
  File "/Users/preshah/redlock-auto/venv3.7/lib/python3.7/site-packages/locust/core.py", line 361, in run
    self.execute_next_task()
  File "/Users/preshah/redlock-auto/venv3.7/lib/python3.7/site-packages/locust/core.py", line 387, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/Users/preshah/redlock-auto/venv3.7/lib/python3.7/site-packages/locust/core.py", line 399, in execute_task
    task(self, *args, **kwargs)
  File "/Users/preshah/redlock-auto/redlockperf/compliance_dashboard_perf/dashboard_phase_3.py", line 67, in get_report_post_response
    verify=False, name=payload)
  File "/Users/preshah/redlock-auto/venv3.7/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/preshah/redlock-auto/venv3.7/lib/python3.7/site-packages/locust/clients.py", line 147, in request
    response_length=request_meta["content_size"],
  File "/Users/preshah/redlock-auto/venv3.7/lib/python3.7/site-packages/locust/events.py", line 34, in fire
    handler(**kwargs)
  File "/Users/preshah/redlock-auto/venv3.7/lib/python3.7/site-packages/locust/stats.py", line 558, in on_request_success
    global_stats.log_request(request_type, name, response_time, response_length)
  File "/Users/preshah/redlock-auto/venv3.7/lib/python3.7/site-packages/locust/stats.py", line 94, in log_request
    self.get(name, method).log(response_time, content_length)
  File "/Users/preshah/redlock-auto/venv3.7/lib/python3.7/site-packages/locust/stats.py", line 112, in get
    entry = self.entries.get((name, method))
TypeError: unhashable type: 'dict'
```
The request goes through successfully and then it shows this error

**Comment by heyman** [comment]
Just from looking at the Stacktrace, i'm *guessing* that maybe `payload` is a dict, and not a string, which I believe could be causing the error.

If you think this is an error in Locust please provide us with a minimal code example that can reproduce the error.
