### ISSUE TITLE
Running into libzmq issue for running locust in a docker container

### ISSUE THREAD

**Issue by kasturichavan** [locustio/locust#1096]
#### Running locust command in docker seems to fail with this error `ImportError: libzmq.so.5: cannot open shared object file: No such file or directory`

`docker-compose run performance_test
[root@ff6a30527995 app]# locust
unable to execute 'gcc': No such file or directory
Traceback (most recent call last):
  File "/pyenv/versions/mats/bin/locust", line 7, in <module>
    from locust.main import main
  File "/pyenv/versions/3.6.2/envs/mats/lib/python3.6/site-packages/locust/__init__.py", line 1, in <module>
    from .core import HttpLocust, Locust, TaskSet, TaskSequence, task, seq_task
  File "/pyenv/versions/3.6.2/envs/mats/lib/python3.6/site-packages/locust/core.py", line 23, in <module>
    from .runners import STATE_CLEANUP
  File "/pyenv/versions/3.6.2/envs/mats/lib/python3.6/site-packages/locust/runners.py", line 18, in <module>
    from .rpc import Message, rpc
  File "/pyenv/versions/3.6.2/envs/mats/lib/python3.6/site-packages/locust/rpc/__init__.py", line 1, in <module>
    from . import zmqrpc as rpc
  File "/pyenv/versions/3.6.2/envs/mats/lib/python3.6/site-packages/locust/rpc/zmqrpc.py", line 1, in <module>
    import zmq.green as zmq
  File "/pyenv/versions/3.6.2/envs/mats/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/pyenv/versions/3.6.2/envs/mats/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/pyenv/versions/3.6.2/envs/mats/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/pyenv/versions/3.6.2/envs/mats/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/pyenv/versions/3.6.2/envs/mats/lib/python3.6/site-packages/zmq/backend/select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/pyenv/versions/3.6.2/envs/mats/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libzmq.so.5: cannot open shared object file: No such file or directory
`

### Expected behavior

Docker container via requirements.txt is pip installing locustio and other packages.
`Successfully installed certifi-2019.9.11 chardet-3.0.4 idna-2.8 locustio-0.11.0 msgpack-0.6.1 pyzmq-18.1.0 r`

So running locust command in container should work. 

Note: Manually running locust command in container gives above mentioned error. And when running locust command via entrypoint docker sh 

`#!/bin/bash

LOCUST="locust"
LOCUS_OPTS="-f locustfile.py --host=$TARGET_HOST"
LOCUST_MODE=${LOCUST_MODE:-standalone}
if [[ "$LOCUST_MODE" = "master" ]]; then
    LOCUS_OPTS="$LOCUS_OPTS --master"
elif [[ "$LOCUST_MODE" = "worker" ]]; then
    LOCUS_OPTS="$LOCUS_OPTS --slave --master-host=$LOCUST_MASTER"
fi
echo "$LOCUST $LOCUS_OPTS"
$LOCUST $LOCUS_OPTS ` 
**I get  locust- command not found**

### Environment settings
- OS:
- Python version: 3.6
- Locust version: 0.11.0

**Comment by max-rocket-internet** [comment]
What docker image are you using? From current master:

```
~/git/locust$ docker build . -t test1
Sending build context to Docker daemon  3.434MB
Step 1/11 : FROM python:3.6.6-alpine3.8 as builder
 ---> a78e257617d1
Step 2/11 : RUN apk --no-cache add g++ zeromq-dev
 ---> Using cache
 ---> 60b96fb16879
Step 3/11 : RUN pip install locustio pyzmq
 ---> Using cache
 ---> 171f5db05368
Step 4/11 : FROM python:3.6.6-alpine3.8
 ---> a78e257617d1
Step 5/11 : RUN apk --no-cache add zeromq-dev
 ---> Using cache
 ---> 4e967f6919bc
Step 6/11 : COPY --from=builder /usr/local/lib/python3.6/site-packages /usr/local/lib/python3.6/site-packages
 ---> Using cache
 ---> 70711432b49f
Step 7/11 : COPY --from=builder /usr/local/bin/locust /usr/local/bin/locust
 ---> Using cache
 ---> 34842e21057f
Step 8/11 : COPY docker_start.sh docker_start.sh
 ---> Using cache
 ---> ce0c305b2203
Step 9/11 : RUN chmod +x docker_start.sh
 ---> Using cache
 ---> 85e1a7f0ec0c
Step 10/11 : EXPOSE 8089 5557 5558
 ---> Using cache
 ---> 3dd9be4d516d
Step 11/11 : ENTRYPOINT ["./docker_start.sh"]
 ---> Using cache
 ---> 618bd947f490
Successfully built 618bd947f490
Successfully tagged test1:latest

$ docker run --entrypoint "" -it test1 locust --help
Usage: locust [options] [LocustClass [LocustClass2 ... ]]
```

Locust command runs:

```
Options:
  -h, --help            show this help message and exit
  -H HOST, --host=HOST  Host to load test in the following format:
                        http://10.21.32.33
  --web-host=WEB_HOST   Host to bind the web interface to. Defaults to '' (all
...
```
