### ISSUE TITLE
Auth locust problem

### ISSUE THREAD

**Issue by rahmounimed** [locustio/locust#1121]
def base_auth(self):
    self.client.request(method="GET", url="/", auth=HTTPDigestAuth("admin", "password"))

[2019-10-24 12:06:16,752] ubuntu/ERROR/stderr: Traceback (most recent call last):
[2019-10-24 12:06:16,752] ubuntu/ERROR/stderr: File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
[2019-10-24 12:06:16,752] ubuntu/ERROR/stderr: File "/opt/odoo10/venv-odoo10/local/lib/python2.7/site-packages/locust/runners.py", line 114, in start_locust
[2019-10-24 12:06:16,752] ubuntu/ERROR/stderr: locust().run(runner=self)
[2019-10-24 12:06:16,752] ubuntu/ERROR/stderr: File "/opt/locust/locust/locustfile.py", line 29, in __init__
[2019-10-24 12:06:16,752] ubuntu/ERROR/stderr: super(AtoutConnectBehavior, self).__init__(*args, **kwargs)
[2019-10-24 12:06:16,752] ubuntu/ERROR/stderr: File "/opt/locust/locust/OdooLocust/OdooLocust.py", line 72, in __init__
[2019-10-24 12:06:16,752] ubuntu/ERROR/stderr: self._connect()
[2019-10-24 12:06:16,752] ubuntu/ERROR/stderr: File "/opt/locust/locust/OdooLocust/OdooLocust.py", line 82, in _connect
[2019-10-24 12:06:16,752] ubuntu/ERROR/stderr: self.rpc.check_login()
[2019-10-24 12:06:16,752] ubuntu/ERROR/stderr: File "/opt/odoo10/venv-odoo10/local/lib/python2.7/site-packages/openerplib/main.py", line 243, in check_login
[2019-10-24 12:06:16,752] ubuntu/ERROR/stderr: self.user_id = self.get_service("common").login(self.database, self.login, self.password)
[2019-10-24 12:06:16,752] ubuntu/ERROR/stderr: File "/opt/odoo10/venv-odoo10/local/lib/python2.7/site-packages/openerplib/main.py", line 180, in proxy
[2019-10-24 12:06:16,753] ubuntu/ERROR/stderr: result = self.connector.send(self.service_name, method, *args)
[2019-10-24 12:06:16,753] ubuntu/ERROR/stderr: File "/opt/locust/locust/OdooLocust/OdooLocust.py", line 51, in send
[2019-10-24 12:06:16,753] ubuntu/ERROR/stderr: raise e
[2019-10-24 12:06:16,753] ubuntu/ERROR/stderr: URLError: <urlopen error [Errno 111] Connection refused>

Odoo JsonRPC common : login: "URLError(error(111, 'Connection refused'),)"

**Comment by heyman** [comment]
Please  follow the bug report template.
