### ISSUE TITLE
Error while installing Locust on Windows

### ISSUE THREAD

**Issue by mhdmaktabi** [locustio/locust#1147]

**Comment by mhdmaktabi** [comment]
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\user\AppData\Local\Programs\Python\Python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-jliu0naz\\gevent\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-jliu0naz\\gevent\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-install-jliu0naz\gevent\pip-egg-info'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-jliu0naz\gevent\
    Complete output (112 lines):
    Traceback (most recent call last):
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\MUHAMM~1.MEK\AppData\Local\Temp\easy_install-y5uh6wsp\cffi-1.13.2\setup.py", line 127, in <module>
        HUB_PRIMITIVES = Extension(name="gevent.__hub_primitives",
      File "C:\Users\MUHAMM~1.MEK\AppData\Local\Temp\easy_install-y5uh6wsp\cffi-1.13.2\setup.py", line 105, in uses_msvc
        include_dirs=include_dirs)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\config.py", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\config.py", line 127, in _compile
        src = self._gen_temp_sourcefile(body, headers, lang)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\config.py", line 109, in _gen_temp_sourcefile
        with open(filename, "w") as file:
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 418, in _open
        self._violation("open", path, mode, *args, **kw)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 407, in _violation
        raise SandboxViolation(operation, args, kw)
    setuptools.sandbox.SandboxViolation: SandboxViolation: open('_configtest.c', 'w') {}

    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.

    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-jliu0naz\gevent\setup.py", line 427, in <module>
        run_setup(EXT_MODULES, run_make=_BUILDING)
      File "C:\Users\user\AppData\Local\Temp\pip-install-jliu0naz\gevent\setup.py", line 328, in run_setup
        setup(
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
        raise
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\MUHAMM~1.MEK\AppData\Local\Temp\easy_install-y5uh6wsp\cffi-1.13.2\setup.py", line 127, in <module>
        HUB_PRIMITIVES = Extension(name="gevent.__hub_primitives",
      File "C:\Users\MUHAMM~1.MEK\AppData\Local\Temp\easy_install-y5uh6wsp\cffi-1.13.2\setup.py", line 105, in uses_msvc
        include_dirs=include_dirs)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\config.py", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\config.py", line 127, in _compile
        src = self._gen_temp_sourcefile(body, headers, lang)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\config.py", line 109, in _gen_temp_sourcefile
        with open(filename, "w") as file:
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 418, in _open
        self._violation("open", path, mode, *args, **kw)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 407, in _violation
        raise SandboxViolation(operation, args, kw)
    setuptools.sandbox.SandboxViolation: SandboxViolation: open('_configtest.c', 'w') {}

    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.

    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by heyman** [comment]
Sounds related to #1131 and it's most likely an error in your environment.

However, there is no way for us to debug this issue when you post nothing but a stacktrace. You need to provide as much information as possible for us to be able to reproduce it. This includes Windows version, python version, version of pip and setuptools, etc. etc.

**Comment by heyman** [comment]
Closing this for now, but feel free to post more information, and then we can consider re-opening it.

**Comment by SidharthLala1** [comment]
@heyman Here is ther error i am getting on Windows  10 when in stalling Locsut using the command : pip install locustio

PS D:\Docker Sample Projects\cmder> pip install locust
Collecting locust
![locust_error](https://user-images.githubusercontent.com/33153967/78460944-e54df780-76e2-11ea-944f-96a41ce20680.JPG)

  Downloading locust-0.0.tar.gz (833 bytes)
Collecting locustio
  Using cached locustio-0.14.5-py3-none-any.whl (262 kB)
Requirement already satisfied: msgpack>=0.6.2 in d:\softwares\python\python38-32\lib\site-packages (from locustio->locust) (1.0.0)
Requirement already satisfied: psutil>=5.6.7 in d:\softwares\python\python38-32\lib\site-packages (from locustio->locust) (5.7.0)
Requirement already satisfied: flask>=0.10.1 in d:\softwares\python\python38-32\lib\site-packages (from locustio->locust) (1.1.2)
Requirement already satisfied: requests>=2.9.1 in d:\softwares\python\python38-32\lib\site-packages (from locustio->locust) (2.23.0)
Requirement already satisfied: ConfigArgParse>=1.0 in d:\softwares\python\python38-32\lib\site-packages (from locustio->locust) (1.2)
Requirement already satisfied: gevent==1.5a3 in d:\softwares\python\python38-32\lib\site-packages (from locustio->locust) (1.5a3)
Collecting geventhttpclient-wheels==1.3.1.dev2
  Using cached geventhttpclient-wheels-1.3.1.dev2.tar.gz (54 kB)
Requirement already satisfied: pyzmq>=16.0.2 in d:\softwares\python\python38-32\lib\site-packages (from locustio->locust) (19.0.0)
Requirement already satisfied: click>=5.1 in d:\softwares\python\python38-32\lib\site-packages (from flask>=0.10.1->locustio->locust) (7.1.1)
Requirement already satisfied: Werkzeug>=0.15 in d:\softwares\python\python38-32\lib\site-packages (from flask>=0.10.1->locustio->locust) (1.0.1)
Requirement already satisfied: Jinja2>=2.10.1 in d:\softwares\python\python38-32\lib\site-packages (from flask>=0.10.1->locustio->locust) (2.11.1)
Requirement already satisfied: itsdangerous>=0.24 in d:\softwares\python\python38-32\lib\site-packages (from flask>=0.10.1->locustio->locust) (1.1.0)
Requirement already satisfied: chardet<4,>=3.0.2 in d:\softwares\python\python38-32\lib\site-packages (from requests>=2.9.1->locustio->locust) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in d:\softwares\python\python38-32\lib\site-packages (from requests>=2.9.1->locustio->locust) (2019.11.28)
Requirement already satisfied: idna<3,>=2.5 in d:\softwares\python\python38-32\lib\site-packages (from requests>=2.9.1->locustio->locust) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in d:\softwares\python\python38-32\lib\site-packages (from requests>=2.9.1->locustio->locust) (1.25.8)
Requirement already satisfied: greenlet>=0.4.14; platform_python_implementation == "CPython" in d:\softwares\python\python38-32\lib\site-packages (from gevent==1.5a3->locustio->locust) (0.4.15)
Requirement already satisfied: cffi>=1.12.2; platform_python_implementation == "CPython" and sys_platform == "win32" in d:\softwares\python\python38-32\lib\site-packages (from gevent==1.5a3->locustio->locust) (1.14.0)
Requirement already satisfied: six in d:\softwares\python\python38-32\lib\site-packages (from geventhttpclient-wheels==1.3.1.dev2->locustio->locust) (1.14.0)
Requirement already satisfied: MarkupSafe>=0.23 in d:\softwares\python\python38-32\lib\site-packages (from Jinja2>=2.10.1->flask>=0.10.1->locustio->locust) (1.1.1)
Requirement already satisfied: pycparser in d:\softwares\python\python38-32\lib\site-packages (from cffi>=1.12.2; platform_python_implementation == "CPython" and sys_platform == "win32"->gevent==1.5a3->locustio->locust) (2.20)
Installing collected packages: geventhttpclient-wheels, locustio, locust
    Running setup.py install for geventhttpclient-wheels ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\softwares\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sidha\\AppData\\Local\\Temp\\pip-install-l2qh2xpq\\geventhttpclient-wheels\\setup.py'"'"'; __file__='"'"'C:\\Users\\sidha\\AppData\\Local\\Temp\\pip-install-l2qh2xpq\\geventhttpclient-wheels\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\sidha\AppData\Local\Temp\pip-record-s3e3z335\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\softwares\python\python38-32\Include\geventhttpclient-wheels'
         cwd: C:\Users\sidha\AppData\Local\Temp\pip-install-l2qh2xpq\geventhttpclient-wheels\
    Complete output (43 lines):
    d:\softwares\python\python38-32\lib\site-packages\setuptools\dist.py:471: UserWarning: Normalizing '1.3.1dev2' to '1.3.1.dev2'
      warnings.warn(
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\geventhttpclient
    copying src\geventhttpclient\client.py -> build\lib.win32-3.8\geventhttpclient
    copying src\geventhttpclient\connectionpool.py -> build\lib.win32-3.8\geventhttpclient
    copying src\geventhttpclient\header.py -> build\lib.win32-3.8\geventhttpclient
    copying src\geventhttpclient\httplib.py -> build\lib.win32-3.8\geventhttpclient
    copying src\geventhttpclient\response.py -> build\lib.win32-3.8\geventhttpclient
    copying src\geventhttpclient\url.py -> build\lib.win32-3.8\geventhttpclient
    copying src\geventhttpclient\useragent.py -> build\lib.win32-3.8\geventhttpclient
    copying src\geventhttpclient\__init__.py -> build\lib.win32-3.8\geventhttpclient
    running egg_info
    writing src\geventhttpclient_wheels.egg-info\PKG-INFO
    writing dependency_links to src\geventhttpclient_wheels.egg-info\dependency_links.txt
    writing requirements to src\geventhttpclient_wheels.egg-info\requires.txt
    writing top-level names to src\geventhttpclient_wheels.egg-info\top_level.txt
    reading manifest file 'src\geventhttpclient_wheels.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    writing manifest file 'src\geventhttpclient_wheels.egg-info\SOURCES.txt'
    creating build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\oncert.pem -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\server.crt -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\server.key -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_client.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_headers.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_httplib.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_keep_alive.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_network_failures.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_no_module_ssl.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_parser.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_ssl.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_url.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_useragent.py -> build\lib.win32-3.8\geventhttpclient\tests
    running build_ext
    building 'geventhttpclient._parser' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\softwares\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sidha\\AppData\\Local\\Temp\\pip-install-l2qh2xpq\\geventhttpclient-wheels\\setup.py'"'"'; __file__='"'"'C:\\Users\\sidha\\AppData\\Local\\Temp\\pip-install-l2qh2xpq\\geventhttpclient-wheels\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\sidha\AppData\Local\Temp\pip-record-s3e3z335\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\softwares\python\python38-32\Include\geventhttpclient-wheels' Check the logs for full command output.

**Comment by heyman** [comment]
@SidharthLala1:
There is no prebuilt wheel for Python 3.8 in the geventhttpclient-wheels package yet. Try with Python 3.7 or Python 3.6.

**Comment by ShivKJ** [comment]
@heyman 
Is this issue resolved for python3.8?
