### ISSUE TITLE
Cannot implement database load testing because I have to override Locust class

### ISSUE THREAD

**Issue by gfalcone** [locustio/locust#1163]
### Describe the bug

Hi ! 

I am trying to implement a database load testing with Locust ! I tried following this article https://docs.locust.io/en/latest/testing-other-systems.html and here is the code I implemented to test my Teradata database : 

```python
import time

import teradatasql

from locust import Locust, TaskSet, events, task, between

USER = 'coconut'
PASSWORD = 'coconut'


class TeradataClient(object):

    def __init__(self, host, user, password):
        self.conn = teradatasql.connect(
            host=host,
            user=user,
            password=password
        )
        self.cursor = self.conn.cursor()

    def execute(self, query):
        start_time = time.time()
        try:
            self.cursor.execute(query)
        except teradatasql.Error as e:
            total_time = int((time.time() - start_time) * 1000)
            events.request_failure.fire(request_type="teradata", name='TeradataClient', response_time=total_time, exception=e)  # NOQA
        else:
            total_time = int((time.time() - start_time) * 1000)
            events.request_failure.fire(request_type="generic", name='TeradataClient', response_time=total_time, response_length=0)  # NOQA


class TeradataLocust(Locust):
    def __int__(self, *args, **kwargs):
        super(TeradataLocust, self).__init__(*args, **kwargs)
        self.client = TeradataClient(self.host, USER, PASSWORD)


class UplayUser(TeradataLocust):

    host = 'edw-prod.coconut.org'
    wait_time = between(0.1, 1)

    class task_set(TaskSet):
        @task(2)
        def get_cohort_r6_with_played_platform(self):
            query = """
            SELECT COHORT_NB, 
                INSTALLMENT_DESCRIPTION, 
                PLAYED_PLATFORM_SHORT_DESCRIPTION, 
                EXTRACT(MONTH FROM MONTH_LAST_DAY_DATE), 
                SUM(NB_ACTIVE_PLAYERS), 
                SUM(NB_SESSION_DAYS), 
                SUM(NB_SESSION_DAYS) / SUM(NB_ACTIVE_PLAYERS)
            FROM COCONUT.FT_ACTIVITY_COHORT_AGG_VW
            WHERE INSTALLMENT_DESCRIPTION='COCONUT'
            GROUP BY COHORT_NB, 
                INSTALLMENT_DESCRIPTION, 
                PLAYED_PLATFORM_SHORT_DESCRIPTION, 
                EXTRACT(MONTH FROM MONTH_LAST_DAY_DATE)
            """
            self.client.execute(query)

        @task(3)
        def get_cohort_r6_with_installment_description(self):
            query = """
            SELECT 
                COHORT_NB, 
                INSTALLMENT_DESCRIPTION, 
                EXTRACT(MONTH FROM MONTH_LAST_DAY_DATE), 
                SUM(NB_ACTIVE_PLAYERS), 
                SUM(NB_SESSION_DAYS), 
                SUM(NB_SESSION_DAYS) / SUM(NB_ACTIVE_PLAYERS)
            FROM COCONUT.FT_ACTIVITY_COHORT_AGG_VW
            WHERE INSTALLMENT_DESCRIPTION='COCONUT'
            GROUP BY 
                COHORT_NB, 
                INSTALLMENT_DESCRIPTION, 
                EXTRACT(MONTH FROM MONTH_LAST_DAY_DATE)
            """
            self.client.execute(query)

        @task(1)
        def get_cohort_with_installment_description(self):
            query = """
            SELECT 
                COHORT_NB, 
                INSTALLMENT_DESCRIPTION, 
                EXTRACT(MONTH FROM MONTH_LAST_DAY_DATE), 
                SUM(NB_ACTIVE_PLAYERS), 
                SUM(NB_SESSION_DAYS), 
                SUM(NB_SESSION_DAYS) / SUM(NB_ACTIVE_PLAYERS)
            FROM COCONUT.FT_ACTIVITY_COHORT_AGG_VW
            GROUP BY 
                COHORT_NB, 
                INSTALLMENT_DESCRIPTION, 
                EXTRACT(MONTH FROM MONTH_LAST_DAY_DATE)
            """
            self.client.execute(query)
```
### Expected behavior
It should work ! 

### Actual behavior
I get the following stack trace : 

````
[2019-11-19 18:00:55,855] CUV-LAP-082808/ERROR/stderr: Traceback (most recent call last):
  File "c:\users\pgenisselmonsallier\projects\aads\load_testing\venv\lib\site-packages\locust\core.py", line 394, in run
    self.execute_next_task()
  File "c:\users\pgenisselmonsallier\projects\aads\load_testing\venv\lib\site-packages\locust\core.py", line 424, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "c:\users\pgenisselmonsallier\projects\aads\load_testing\venv\lib\site-packages\locust\core.py", line 436, in execute_task
    task(self, *args, **kwargs)
  File "C:\Users\pgenisselmonsallier\Projects\aads\load_testing\sql_load_testing.py", line 81, in get_cohort_r6_with_installment_description
    self.client.execute(query)
  File "c:\users\pgenisselmonsallier\projects\aads\load_testing\venv\lib\site-packages\locust\core.py", line 96, in __getattr__
    raise LocustError("No client instantiated. Did you intend to inherit from HttpLocust?")

````

It seems that I cannot override the Locust class, which is the way showed in the documentation for this specific case. How can I implement this in another way ? Should I disable the exception ? 

### Steps to reproduce

```bash
locust -f my_file.py
````

### Environment settings

- OS: Windows
- Python version: 3.7
- Locust version: 0.13.2

Thank you in advance for your help !

**Comment by heyman** [comment]
You've misspelled `TeradataLocust.__init__` (it currently says `__int__`). Let me know if that fixes it!

**Comment by gfalcone** [comment]
You're right ! I should have noticed this. Sorry for the inconvenience
