### ISSUE TITLE
Got error using locust when it is installed using python -m

### ISSUE THREAD

**Issue by zeinababbasi** [locustio/locust#1169]
### Description
I have installed **locust** as explained in the docs with `python3 -m pip install locustio` and the installation process has returned no errors. But when I called `locust --help`, I got this error:
```
Traceback (most recent call last):
  File "/home/zeinab/.local/bin/locust", line 7, in <module>
    from locust.main import main
  File "/home/zeinab/.local/lib/python3.6/site-packages/locust/__init__.py", line 1, in <module>
    from .core import HttpLocust, Locust, TaskSet, TaskSequence, task, seq_task
  File "/home/zeinab/.local/lib/python3.6/site-packages/locust/core.py", line 17, in <module>
    monkey.patch_all()
  File "/home/zeinab/.local/lib/python3.6/site-packages/gevent/monkey.py", line 1087, in patch_all
    _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
  File "/home/zeinab/.local/lib/python3.6/site-packages/gevent/monkey.py", line 173, in _notify_patch
    notify_and_call_entry_points(event)
  File "/home/zeinab/.local/lib/python3.6/site-packages/gevent/events.py", line 112, in notify_and_call_entry_points
    subscriber = plugin.load()
  File "/home/zeinab/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/home/zeinab/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/zeinab/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psutil>=5.6.1; platform_python_implementation == "CPython" or sys_platform != "win32" and extra == "recommended"' distribution was not found and is required by the application
```

I tried to install it using pip directly; i.e. `pip3 install locustio`. This time it was installed completely and calling **locust** returns no error. 
While installing the **locustio** with the second approach, the **pip3** installed **psutil** which was not installed when using first command:
```
Collecting psutil>=5.6.1; platform_python_implementation == "CPython" or sys_platform != "win32" and extra == "recommended" (from gevent==1.5a2->locustio)

  Downloading https://files.pythonhosted.org/packages/03/9a/95c4b3d0424426e5fd94b5302ff74cea44d5d4f53466e1228ac8e73e14b4/psutil-5.6.5.tar.gz (447kB)
    100% |████████████████████████████████| 450kB 460kB/s 
```

### Environment settings
- OS: Ubuntu 18.04
- Python version: 3.7.6; it is installed inside a virtual environment which was created using **pyenv**.
- Locust version: 0.13.2

**Comment by eranif** [comment]
Same thing. Installed `locust` on `Ubuntu 18.04`. Using the suggested workaround fixed the problem for me.

**Comment by cyberw** [comment]
No updates from contributor.
