### ISSUE TITLE
 ModuleNotFoundError: No module named 'locust

### ISSUE THREAD

**Issue by mhdmaktabi** [locustio/locust#1207]
Hi,

When I try to run my script test I got this error:
ModuleNotFoundError: No module named 'locust'

The Log:

Traceback (most recent call last):
  File "c:\users\username\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\username\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\Scripts\locust.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'locust'

### Environment settings

- OS: Windows
- Python version: 3.7

**Comment by cyberw** [comment]
Sounds like you havent (successfully) installed locust?
