### ISSUE TITLE
Can't access web interface

### ISSUE THREAD

**Issue by agniveshadhikari** [locustio/locust#1288]
### Describe the bug
Can't access web interface

### Expected behavior
Should be able to access web interface at 127.0.0.1:8089 or localhost:8089

### Actual behavior
Not able to access web interface at 127.0.0.1:8089 or localhost:8089

### Steps to reproduce
`$ locust` 

### Environment

- OS: Win10
- Python version: 3.6.8
- Locust version: 0.14.5
- Locust command line that you ran: locust
- Locust file contents (anonymized if necessary):

```
from locust import HttpLocust, TaskSet, task, between
from msal import PublicClientApplication

class UserBehaviour(TaskSet):
    def on_start(self):
        print("on_start called")
        self.app = PublicClientApplication(
            "<app id>",
            authority="<aad authority>")

        result = self.app.acquire_token_by_username_password(
            "<user creds>",
            "<user creds>",
            scopes=[
                "<microsoft aad scope>",
            ]
        )

        if not result:
            raise Exception("result is empty, couldn't get first tokem")

        print("on_start completed")



    def on_stop(self):
        """ on_stop is called when the TaskSet is stopping """
        pass

    def getToken(self):
        return self.app.acquire_token_silent(
            ["<microsoft aad scope>"],
            account=self.app.get_accounts()[0]
        )['access_token']
    

    @task(1)
    def farmGetAll(self):
        token = self.getToken()
        self.client.get("/Farm", headers={"Authorization": "Bearer " + token}, verify=False)

    @task(1)
    def ruleGetAll(self):
        token = self.getToken()
        self.client.get("/Rule", headers={"Authorization": "Bearer " + token}, verify=False)

class WebsiteUser(HttpLocust):
    task_set = UserBehaviour
    wait_time = between(2, 5)
```

Logs from the console:
```
[2020-03-12 14:41:36,066] DESKTOP-SF6MB84/INFO/locust.main: Starting web monitor at http://*:8089
[2020-03-12 14:41:36,066] DESKTOP-SF6MB84/INFO/locust.main: Starting Locust 0.14.5
[2020-03-12 14:41:44,334] DESKTOP-SF6MB84/ERROR/stderr: Traceback (most recent call last):
[2020-03-12 14:41:44,335] DESKTOP-SF6MB84/ERROR/stderr: 
[2020-03-12 14:41:44,335] DESKTOP-SF6MB84/ERROR/stderr: File "c:\users\agadhika\appdata\local\programs\python\python36\lib\site-packages\gevent\pywsgi.py", line 666, in handle_one_request
    if not self.read_request(self.requestline):
[2020-03-12 14:41:44,336] DESKTOP-SF6MB84/ERROR/stderr:
[2020-03-12 14:41:44,341] DESKTOP-SF6MB84/ERROR/stderr: File "c:\users\agadhika\appdata\local\programs\python\python36\lib\site-packages\gevent\pywsgi.py", line 531, in read_request
    raise _InvalidClientRequest('Invalid HTTP method: %r' % (raw_requestline,))
[2020-03-12 14:41:44,342] DESKTOP-SF6MB84/ERROR/stderr:
[2020-03-12 14:41:44,343] DESKTOP-SF6MB84/ERROR/stderr: gevent.pywsgi._InvalidClientRequest: Invalid HTTP method: '\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x0389zya´RMæÇù*\x87\x10\x9d\x1bYíS¹Û\x05IÍK\rÅÝ\x85\x8fX¨ Ý£bæ\x86p´ú\x10ÁaÎL´×(Ñð`%al\x08Ý?\x0e[©p\t\x1cQ\x00"ÚÚ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00\n'
```

At localhost:8089, chrome says:
```
This site can’t provide a secure connectionlocalhost sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR
```

At 127.0.0.1:8089, chrome says:
```
This site can’t be reached127.0.0.1 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```

**Comment by heyman** [comment]
It sound like you're maybe trying to access the web UI through http**s**? Make sure that the URL you're trying to access it: http://127.0.0.1:8089

**Comment by agniveshadhikari** [comment]
@heyman You are right. My google chrome now defaults to https for localhost. Works fine on other browsers. However, can the log outputs be made better?
`'\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x0389zya´RMæÇù*\x87\x10\x9d\x1bYíS¹Û\x05IÍK\rÅÝ\x85\x8fX¨ Ý£bæ\x86p´ú\x10ÁaÎL´×(Ñð`%al\x08Ý?\x0e[©p\t\x1cQ\x00"ÚÚ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00\n'` doesn't help too much.

Closing. Thanks for the help!
