### ISSUE TITLE
requests library uses "wheel" file

### ISSUE THREAD

**Issue by cbrinley** [locustio/locust#134]
```
This is arguably not a locust issue but I wanted to make you aware of it. Full acknowledgement that I may have also done something dumb by accident.

On a new RHEL AWS server running "pip install locust" finishes correctly.
When running "locust --help" or any other command line variant the package manager raises following exception:

root@AWS_HOST scripts]# locust --help
Traceback (most recent call last):
  File "/usr/bin/locust", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.2

Upon further investigation this appears to be due to the fact that the latest pip install of requests uses Wheel now instead of egg format. As a result the following logic fails in package manager:

> /usr/lib/python2.6/site-packages/pkg_resources.py(1694)find_on_path()->None
-> for entry in os.listdir(path_item):
(Pdb) l
1689 	                    path_item, os.path.join(path_item,'EGG-INFO')
1690 	                )
1691 	            )
1692 	        else:
1693 	            # scan for .egg and .egg-info in directory
1694 	            for entry in os.listdir(path_item):
1695 	                lower = entry.lower()
1696 -> 	                if lower.endswith('.egg-info'):
1697 	                    fullpath = os.path.join(path_item, entry)
1698 	                    if os.path.isdir(fullpath):
1699 	                        # egg-info directory, allow getting metadata


Installing requests from source via setup.py creates the egg-info file and fixes this issue.

I am not currently very familiar with this wheel format but will investigate further to see if there is a simple work around. 
```

**Comment by katkorian** [comment]
Had a similar issue on RHEL6 - python2.6.

Steps:
* fresh RHEL6 host
```
$ uname -r
2.6.32-431.23.3.el6.x86_64
```
* download and run latest get-pip.py
* sudo pip install locustio

```
Collecting MarkupSafe (from Jinja2>=2.4->flask>=0.10.1->locustio)
  Using cached MarkupSafe-0.23.tar.gz
Building wheels for collected packages: locustio, gevent, flask, msgpack-python, greenlet, itsdangerous, MarkupSafe
  Running setup.py bdist_wheel for locustio
  Complete output from command /usr/bin/python -c "import setuptools;__file__='/tmp/pip-build-onsSZr/locustio/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpfRfFg1pip-wheel-:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for locustio
```
* installation continues and finishes with more failed errors for each dependent packages, last line is
```
Successfully installed Jinja2-2.8 MarkupSafe-0.23 Werkzeug-0.10.4 flask-0.10.1 gevent-1.0.2 greenlet-0.4.7 itsdangerous-0.24 locustio-0.7.3 msgpack-python-0.4.6 requests-2.7.0
```
* As @cbrinley mentioned, locust --help fails with error

### Fix

Based on the trace and changes in *pip*, below steps fixed the issue for me.

```
$ pip wheel
ERROR: 'pip wheel' requires setuptools >= 0.8 for dist-info support. To fix this, run: pip install --upgrade setuptools

$ sudo pip install --upgrade setuptools

$ pip wheel locustio
```
