### ISSUE TITLE
Distributed command line cannot run 

### ISSUE THREAD

**Issue by MarcSteven** [locustio/locust#1458]
### Describe the bug

I use the command to run but cannot start a swarming. Please like the picture
` locust -f load.py --master
`[2020-07-01 16:03:38,423] Marcs-MacBook-Pro.local/ERROR/stderr: Traceback (most recent call last):
[2020-07-01 16:03:38,423] Marcs-MacBook-Pro.local/ERROR/stderr: File "/Users/user/PycharmProjects/APILoadTest/venv/bin/locust", line 10, in <module>
[2020-07-01 16:03:38,423] Marcs-MacBook-Pro.local/ERROR/stderr: 
[2020-07-01 16:03:38,423] Marcs-MacBook-Pro.local/ERROR/stderr: sys.exit(main())
[2020-07-01 16:03:38,423] Marcs-MacBook-Pro.local/ERROR/stderr: 
[2020-07-01 16:03:38,423] Marcs-MacBook-Pro.local/ERROR/stderr: File "/Users/user/PycharmProjects/APILoadTest/venv/lib/python3.8/site-packages/locust/main.py", line 495, in main
[2020-07-01 16:03:38,424] Marcs-MacBook-Pro.local/ERROR/stderr: 
[2020-07-01 16:03:38,424] Marcs-MacBook-Pro.local/ERROR/stderr: runners.locust_runner = MasterLocustRunner(locust_classes, options)
[2020-07-01 16:03:38,424] Marcs-MacBook-Pro.local/ERROR/stderr: 
[2020-07-01 16:03:38,424] Marcs-MacBook-Pro.local/ERROR/stderr: File "/Users/user/PycharmProjects/APILoadTest/venv/lib/python3.8/site-packages/locust/runners.py", line 346, in __init__
[2020-07-01 16:03:38,425] Marcs-MacBook-Pro.local/ERROR/stderr: 
[2020-07-01 16:03:38,425] Marcs-MacBook-Pro.local/ERROR/stderr: self.server = rpc.Server(self.master_bind_host, self.master_bind_port)
[2020-07-01 16:03:38,425] Marcs-MacBook-Pro.local/ERROR/stderr: 
[2020-07-01 16:03:38,425] Marcs-MacBook-Pro.local/ERROR/stderr: File "/Users/user/PycharmProjects/APILoadTest/venv/lib/python3.8/site-packages/locust/rpc/zmqrpc.py", line 41, in __init__
[2020-07-01 16:03:38,426] Marcs-MacBook-Pro.local/ERROR/stderr: 
[2020-07-01 16:03:38,426] Marcs-MacBook-Pro.local/ERROR/stderr: self.socket.bind("tcp://%s:%i" % (host, port))
[2020-07-01 16:03:38,426] Marcs-MacBook-Pro.local/ERROR/stderr: 
[2020-07-01 16:03:38,426] Marcs-MacBook-Pro.local/ERROR/stderr: File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
[2020-07-01 16:03:38,426] Marcs-MacBook-Pro.local/ERROR/stderr: File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
[2020-07-01 16:03:38,426] Marcs-MacBook-Pro.local/ERROR/stderr: zmq.error
[2020-07-01 16:03:38,426] Marcs-MacBook-Pro.local/ERROR/stderr: .
[2020-07-01 16:03:38,426] Marcs-MacBook-Pro.local/ERROR/stderr: ZMQError
[2020-07-01 16:03:38,426] Marcs-MacBook-Pro.local/ERROR/stderr: :
[2020-07-01 16:03:38,426] Marcs-MacBook-Pro.local/ERROR/stderr: Address already in use
[2020-07-01 16:03:38,426] Marcs-MacBook-Pro.local/ERROR/stderr: 
`

### Expected behavior

Hope it can run well 

### Actual behavior

Cannot start swarming even though click the button of starting a swarming, it cannot go 
<img width="1648" alt="截屏2020-07-01 下午3 22 40" src="https://user-images.githubusercontent.com/13824297/86215525-420c6180-bbaf-11ea-9ef2-c2ab7baf3d2a.png">

### Environment

- OS: Mac OS
- Python version:3.8
- Locust version:2.4
- Locust command line that you ran: locust -f YouthBombAPI.py --slave
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
`Locust version:2.4`

This version does not exist. What is the output of `locust -V`

**Comment by MarcSteven** [comment]
**locust1.1**
@cyberw

**Comment by cyberw** [comment]
Do you have another instance of locust running? `Address already in use` would suggest the port the master uses to communicate with slaves is busy.

**Comment by MarcSteven** [comment]
Nope， I closed all the instance

**Comment by cyberw** [comment]
Check for any left over python processes. Something must be using that port. Restart your machine if nothing else helps :)

**Comment by MarcSteven** [comment]
Yeah, right, restart it and then it disappeared.

**Comment by cyberw** [comment]
I tried to improve the logging in https://github.com/locustio/locust/pull/1471
