### ISSUE TITLE
self.locust can not be found

### ISSUE THREAD

**Issue by jarvan4dev** [locustio/locust#1470]
version: 1.1

```
# coding=utf-8

from locust import HttpUser, TaskSet, task, between


class Google(TaskSet):
    @task
    def index(self):
        print(self.locust.ids)
        self.client.get("/")


class MyUser(HttpUser):
    tasks = [Google]
    ids = [1, 2]
    wait_time = between(3, 5)
    host = "http://www.google.com"
```

then error occured:
```
[2020-07-07 00:57:02,586] jarvan4devMac.local/ERROR/locust.user.task: 'Google' object has no attribute 'locust'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/locust/user/task.py", line 284, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.7/site-packages/locust/user/task.py", line 309, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.7/site-packages/locust/user/task.py", line 321, in execute_task
    task(self)
  File "/Users/jarvan4dev/Documents/locustfile.py", line 9, in index
    print(self.locust.ids)
AttributeError: 'Google' object has no attribute 'locust'
```

**Comment by jarvan4dev** [comment]
@magupov @cyberw

**Comment by cyberw** [comment]
Try self.user instead of self.locust!

**Comment by jarvan4dev** [comment]
> Try self.user instead of self.locust!

Great, it works!
But I can't find related description for this, can you show me?

**Comment by cyberw** [comment]
https://docs.locust.io/en/stable/writing-a-locustfile.html#referencing-the-user-instance-or-the-parent-taskset-instance
