### ISSUE TITLE
Cant start: Werkzeug: TypeError: code() takes at least 14 arguments (13 given)

### ISSUE THREAD

**Issue by mcjoshua** [locustio/locust#1545]
### Describe the bug

user a simple example

### Actual behavior

C:\Users\Administrator\Desktop\my_locust>locust
[2020-08-26 13:40:22,369] DESKTOP-APUJUVJ/WARNING/locust.main: System open file limit setting is not high enough for load testing, and the OS didn't allow locust to increase it by itself. See https://github.com/locustio/locust/wiki/Installation#increasing-maximum-number-of-open-files-limit for more info.
[2020-08-26 13:40:22,369] DESKTOP-APUJUVJ/INFO/locust.main: Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)
Traceback (most recent call last):
  File "c:\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python38\Scripts\locust.exe\__main__.py", line 7, in <module>
  File "c:\python\python38\lib\site-packages\locust\main.py", line 284, in main
    web_ui = environment.create_web_ui(
  File "c:\python\python38\lib\site-packages\locust\env.py", line 156, in create_web_ui
    self.web_ui = WebUI(self, host, port, auth_credentials=auth_credentials, tls_cert=tls_cert, tls_key=tls_key, stats_csv_writer=stats_csv_writer)
  File "c:\python\python38\lib\site-packages\locust\web.py", line 85, in __init__
    app = Flask(__name__)
  File "c:\python\python38\lib\site-packages\flask\app.py", line 601, in __init__
    self.add_url_rule(
  File "c:\python\python38\lib\site-packages\flask\app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "c:\python\python38\lib\site-packages\flask\app.py", line 1278, in add_url_rule
    self.url_map.add(rule)
  File "c:\python\python38\lib\site-packages\werkzeug\routing.py", line 1562, in add
    rule.bind(self)
  File "c:\python\python38\lib\site-packages\werkzeug\routing.py", line 711, in bind
    self.compile()
  File "c:\python\python38\lib\site-packages\werkzeug\routing.py", line 767, in compile
    self._build = self._compile_builder(False)
  File "c:\python\python38\lib\site-packages\werkzeug\routing.py", line 1128, in _compile_builder
    return self.BuilderCompiler(self).compile(append_unknown)
  File "c:\python\python38\lib\site-packages\werkzeug\routing.py", line 1119, in compile
    co = types.CodeType(*code_args)
TypeError: code() takes at least 14 arguments (13 given)

C:\Users\Administrator\Desktop\my_locust>locust -f lct.py

### Environment

- OS:
- Python version:  3.8
- Locust version:  1.2
- Locust command line that you ran:  locust -f lct.py
- Locust file contents (anonymized if necessary):

lct.py

from locust import HttpUser, task, between

class QuickstartUser(HttpUser):
 
    def on_start(self):
        pass

    @task
    def index_page(self):
        pass

    @task(3)
    def view_item(self):
        pass

**Comment by cyberw** [comment]
Can you check which version of flask and werkzeug you have? (using pip list)

**Comment by mcjoshua** [comment]
> Can you check which version of flask and werkzeug you have? (using pip list)

Flask                   1.1.2
Werkzeug                0.15.2

**Comment by mcjoshua** [comment]
> Can you check which version of flask and werkzeug you have? (using pip list)

when the werkzeug is updated, it can work normally

**Comment by cyberw** [comment]
Huh. Probably we should just pin a higher version of werkzeug to fix this (it has happened before), but the strange thing is that it works for me with 

Flask                          1.1.2 
Werkzeug                       0.15.0
