### ISSUE TITLE
Cannot import name 'HttpUser' from 'locust' error when running Locust in Kubernetes

### ISSUE THREAD

**Issue by galynavasylieva** [locustio/locust#1587]
I am deploying Locust on Kubernetes using Helm Charts(https://github.com/helm/charts/tree/master/stable/locust), which is using Locust container 0.9.0, where HttpUser was HttpLocust.

2 Worker pods are running with no errors, but master is in CrashLoopBackOff status.
Logs are showing following error:

`[2020-10-07 21:46:18,300] locust-master-5bf8d86867-kfxxg/ERROR/stderr: Traceback (most recent call last):
[2020-10-07 21:46:18,300] locust-master-5bf8d86867-kfxxg/ERROR/stderr: File "/usr/local/bin/locust", line 11, in <module>
[2020-10-07 21:46:18,300] locust-master-5bf8d86867-kfxxg/ERROR/stderr: 
[2020-10-07 21:46:18,300] locust-master-5bf8d86867-kfxxg/ERROR/stderr: sys.exit(main())
[2020-10-07 21:46:18,300] locust-master-5bf8d86867-kfxxg/ERROR/stderr: 
[2020-10-07 21:46:18,301] locust-master-5bf8d86867-kfxxg/ERROR/stderr: File "/usr/local/lib/python3.7/site-packages/locust/main.py", line 391, in main
[2020-10-07 21:46:18,301] locust-master-5bf8d86867-kfxxg/ERROR/stderr: 
[2020-10-07 21:46:18,301] locust-master-5bf8d86867-kfxxg/ERROR/stderr: docstring, locusts = load_locustfile(locustfile)
[2020-10-07 21:46:18,301] locust-master-5bf8d86867-kfxxg/ERROR/stderr: 
[2020-10-07 21:46:18,301] locust-master-5bf8d86867-kfxxg/ERROR/stderr: File "/usr/local/lib/python3.7/site-packages/locust/main.py", line 358, in load_locustfile
[2020-10-07 21:46:18,301] locust-master-5bf8d86867-kfxxg/ERROR/stderr: 
[2020-10-07 21:46:18,302] locust-master-5bf8d86867-kfxxg/ERROR/stderr: imported = __import__(os.path.splitext(locustfile)[0])
[2020-10-07 21:46:18,302] locust-master-5bf8d86867-kfxxg/ERROR/stderr: 
[2020-10-07 21:46:18,302] locust-master-5bf8d86867-kfxxg/ERROR/stderr: File "/locust-tasks/tasks.py", line 1, in <module>
[2020-10-07 21:46:18,302] locust-master-5bf8d86867-kfxxg/ERROR/stderr: 
[2020-10-07 21:46:18,302] locust-master-5bf8d86867-kfxxg/ERROR/stderr: from locust import HttpUser, task, TaskSet, between
[2020-10-07 21:46:18,302] locust-master-5bf8d86867-kfxxg/ERROR/stderr: 
[2020-10-07 21:46:18,302] locust-master-5bf8d86867-kfxxg/ERROR/stderr: ImportError
[2020-10-07 21:46:18,302] locust-master-5bf8d86867-kfxxg/ERROR/stderr: :
[2020-10-07 21:46:18,302] locust-master-5bf8d86867-kfxxg/ERROR/stderr: cannot import name 'HttpUser' from 'locust' (/usr/local/lib/python3.7/site-packages/locust/__init__.py)
[2020-10-07 21:46:18,303] locust-master-5bf8d86867-kfxxg/ERROR/stderr:`

Is that possible to update the chart to use 1.0.+ Locust and is it in the roadmap any time soon? Thanks!

- OS: MacOS
- Python version: 3.7
- Locust version: locust==1.2.3
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Hi! The helm chart is not maintained by us. Maybe file a ticket for the helm charts repo? Or check with one of the maintainers for the locust chart specifically? https://github.com/helm/charts/blob/master/stable/locust/OWNERS

**Comment by max-rocket-internet** [comment]
@galynavasylieva FYI the Helm Charts stable repo will be closed next month. Then you will need to find another chart for locust. There's a few old ones around, [e.g.](https://artifacthub.io/packages/helm/presslabs/locust) but I think this is the most up to date best one is here: https://github.com/deliveryhero/helm-charts/tree/master/stable/locust

**Comment by cyberw** [comment]
> @galynavasylieva FYI the Helm Charts stable repo will be closed next month. Then you will need to find another chart for locust. There's a few old ones around, [e.g.](https://artifacthub.io/packages/helm/presslabs/locust) but I think this is the most up to date best one is here: https://github.com/deliveryhero/helm-charts/tree/master/stable/locust

We should link that somewhere. Could you add it to the documentation, or maybe the wiki?

**Comment by galynavasylieva** [comment]
Thank you for your responses, guys!

**Comment by max-rocket-internet** [comment]
> We should link that somewhere. Could you add it to the documentation (under Running Locust with Docker)?

@cyberw I did add a link and brief instructions to a Helm chart previously but @heyman removed it all: https://github.com/max-rocket-internet/locust/commit/995eca8f8760bc679353661db99a77f149a87e23#diff-d0b182f28f3fabdf0c3db81c34c6c49dcb203b118babeac31ecc70c1ae229a69

Should I add it yet again?

**Comment by cyberw** [comment]
Yes, please do!
