### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by camilonova** [locustio/locust#166]
I'm trying to run the demo browsing the locust docs and I'm getting this error:

```
[2014-06-19 16:43:47,263] axc.local/ERROR/stderr: Traceback (most recent call last):
  File ".../lib/python2.7/site-packages/locust/core.py", line 267, in run
    self.execute_next_task()
  File ".../lib/python2.7/site-packages/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File ".../lib/python2.7/site-packages/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File ".../locustfile.py", line 33, in load_sub_page
    url = random.choice(self.urls_on_current_page)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 274, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
```

and at the end I get this error report:

```
GET /en/latest//: 'ConnectionError(MaxRetryError("HTTPConnectionPool(host=\'docs.locust.io\', port=80): Max retries exceeded with url: /en/latest// (Caused by <class \'socket.gaierror\'>: [Errno 8] nodename nor servname provided, or not known)",),)'
GET /en/latest/writing-a-locustfile.html: 'ConnectionError(MaxRetryError("HTTPConnectionPool(host=\'docs.locust.io\', port=80): Max retries exceeded with url: /en/latest/writing-a-locustfile.html (Caused by <class \'socket.gaierror\'>: [Errno 8] nodename nor servname provided, or not known)",),)'
```

It keeps stuck after the first error doing nothing, if I redirect the url to a custom site and check the logs, as soon as the error gets in locusts stops making requests.

I'm using a usual virtualenv with python 2.7 and packages installed by pip.

Thanks.

**Comment by whgibbo** [comment]
I'm having the same issue, what was the solution ?

**Comment by msert29** [comment]
I think you guys need to specify the on_start method and check that you have configured the task decorator before task methods.

**Comment by takirohit** [comment]
Yup, I had the same issue. I was not decorating my task/method with **@task**  After decorating the method, I did not get the error :)

**Comment by renanbastos93** [comment]
I have the same problem, I using a macOS Mojave in a MacMini 2012
