### ISSUE TITLE
Test suite failure (packaging for GNU Guix)

### ISSUE THREAD

**Issue by Apteryks** [locustio/locust#1664]
Hello,

### Describe the bug
I'm packaging `python-locust` for GNU Guix. The current dependencies used are:

```
dependencies: python-configargparse@1.2.3 python-flask-basicauth@0.2.0 python-flask@1.1.2
+ python-gevent@20.9.0 python-geventhttpclient@1.4.4 python-mock@3.0.5 python-msgpack@1.0.0
+ python-psutil@5.7.2 python-pyquery@1.2.17 python-pyzmq@17.1.2 python-requests@2.24.0
+ python-werkzeug@1.0.1
```

### Expected behavior
The test suite should pass.

### Actual behavior
The test suite fails with the following errors:
```
======================================================================
ERROR: test_default_headless_spawn_options (locust.test.test_main.LocustProcessIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-locust-1.4.1.drv-0/locust-1.4.1/locust/test/test_main.py", line 231, in test_default_headless_spawn_options
    subprocess.check_output(
  File "/gnu/store/wwm10m100gnpgw46y52a539lkxzf50f7-python-gevent-20.9.0/lib/python3.8/site-packages/gevent/subprocess.py", line 404, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['locust', '-f', '/tmp/guix-build-python-locust-1.4.1.drv-0/locust-1.4.1/locust/test/mock_locustfile_1608407678_1009326_26670.py', '--host', 'https://test.com/', '--run-time', '1s', '--headless']' returned non-zero exit status 1.

======================================================================
ERROR: test_default_headless_spawn_options_with_shape (locust.test.test_main.LocustProcessIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-locust-1.4.1.drv-0/locust-1.4.1/locust/test/test_main.py", line 272, in test_default_headless_spawn_options_with_shape
    subprocess.check_output(
  File "/gnu/store/wwm10m100gnpgw46y52a539lkxzf50f7-python-gevent-20.9.0/lib/python3.8/site-packages/gevent/subprocess.py", line 404, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['locust', '-f', '/tmp/guix-build-python-locust-1.4.1.drv-0/locust-1.4.1/locust/test/mock_locustfile_1608407679_8408535_8220.py', '--host', 'https://test.com/', '--run-time', '1s', '--headless']' returned non-zero exit status 1.

======================================================================
ERROR: test_web_options (locust.test.test_main.LocustProcessIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gnu/store/27bsphgz4hc261iw4lsi22gvm87y9qm2-python-urllib3-1.25.9/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/gnu/store/27bsphgz4hc261iw4lsi22gvm87y9qm2-python-urllib3-1.25.9/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/gnu/store/27bsphgz4hc261iw4lsi22gvm87y9qm2-python-urllib3-1.25.9/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
  File "/gnu/store/wwm10m100gnpgw46y52a539lkxzf50f7-python-gevent-20.9.0/lib/python3.8/site-packages/gevent/_socket3.py", line 407, in connect
    raise error(err, strerror(err))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gnu/store/27bsphgz4hc261iw4lsi22gvm87y9qm2-python-urllib3-1.25.9/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/gnu/store/27bsphgz4hc261iw4lsi22gvm87y9qm2-python-urllib3-1.25.9/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/gnu/store/q9rm8h9imazsq2c4qiv2yjpvlvliywqb-python-3.8.2/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/gnu/store/q9rm8h9imazsq2c4qiv2yjpvlvliywqb-python-3.8.2/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/gnu/store/q9rm8h9imazsq2c4qiv2yjpvlvliywqb-python-3.8.2/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/gnu/store/q9rm8h9imazsq2c4qiv2yjpvlvliywqb-python-3.8.2/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/gnu/store/q9rm8h9imazsq2c4qiv2yjpvlvliywqb-python-3.8.2/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/gnu/store/27bsphgz4hc261iw4lsi22gvm87y9qm2-python-urllib3-1.25.9/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/gnu/store/27bsphgz4hc261iw4lsi22gvm87y9qm2-python-urllib3-1.25.9/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fffefda5670>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gnu/store/xc0p8gamx973rawzai1xx3d1fyahg55v-python-requests-2.24.0/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/gnu/store/27bsphgz4hc261iw4lsi22gvm87y9qm2-python-urllib3-1.25.9/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/gnu/store/27bsphgz4hc261iw4lsi22gvm87y9qm2-python-urllib3-1.25.9/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=32949): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fffefda5670>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/guix-build-python-locust-1.4.1.drv-0/locust-1.4.1/locust/test/test_main.py", line 315, in test_web_options
    self.assertEqual(200, requests.get("http://127.0.0.1:%i/" % port, timeout=1).status_code)
  File "/gnu/store/xc0p8gamx973rawzai1xx3d1fyahg55v-python-requests-2.24.0/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/gnu/store/xc0p8gamx973rawzai1xx3d1fyahg55v-python-requests-2.24.0/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/gnu/store/xc0p8gamx973rawzai1xx3d1fyahg55v-python-requests-2.24.0/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/gnu/store/xc0p8gamx973rawzai1xx3d1fyahg55v-python-requests-2.24.0/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/gnu/store/xc0p8gamx973rawzai1xx3d1fyahg55v-python-requests-2.24.0/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=32949): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fffefda5670>: Failed to establish a new connection: [Errno 111] Connection refused'))

======================================================================
FAIL: test_skip_logging (locust.test.test_log.TestLoggingOptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-locust-1.4.1.drv-0/locust-1.4.1/locust/test/test_log.py", line 132, in test_skip_logging
    self.assertEqual("running my_task", output.strip())
AssertionError: 'running my_task' != "System open file limit '1024' is below m[250 chars]task"
- running my_task
+ System open file limit '1024' is below minimum setting '10000'. It's not high enough for load testing, and the OS didn't allow locust to increase it by itself. See https://github.com/locustio/locust/wiki/Installation#increasing-maximum-number-of-open-files-limit for more info.
running my_task


======================================================================
FAIL: test_custom_exit_code (locust.test.test_main.LocustProcessIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-locust-1.4.1.drv-0/locust-1.4.1/locust/test/test_main.py", line 199, in test_custom_exit_code
    self.assertEqual(42, proc.returncode)
AssertionError: 42 != -15

======================================================================
FAIL: test_headless_spawn_options_wo_run_time (locust.test.test_main.LocustProcessIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-locust-1.4.1.drv-0/locust-1.4.1/locust/test/test_main.py", line 251, in test_headless_spawn_options_wo_run_time
    self.assertEqual(0, proc.returncode)
AssertionError: 0 != -15

----------------------------------------------------------------------
Ran 320 tests in 90.361s

FAILED (failures=3, errors=3)
Test failed: <unittest.runner.TextTestResult run=320 errors=3 failures=3>
error: Test failed: <unittest.runner.TextTestResult run=320 errors=3 failures=3>
command "python" "-c" "import setuptools, tokenize;__file__='setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))" "test" failed with status 1
```

I think the first two issues might have to do with networking not available in the Guix build container. Is there a mean to skip network dependent tests?

The second catches a warning instead of the expected text; the test seems brittle. Note that I can't do anything about the fs.file-max value (say, using `sysctl -w fs.file-max=500000`), as the build user in the container is not root.

I have no clue about the last one.

### Environment

- OS: Guix System
- Python version: 3.8.2
- Locust version: 1.4.1
- Locust command line that you ran: python setup.py test

**Comment by cyberw** [comment]
Hi! Sorry, but this is way out of scope for the project. Probably you should just not run the unit tests at all. Running a reduced test set that doesnt require any network may be possible, but doesnt make a whole lot of sense...

**Comment by Apteryks** [comment]
Hi, thanks for your answer.

Actually, only `test_web_options` seems to fail for lack of networking.

For the record, I've used pytest to run the test suit, as it allows skipping tests easily from the command line.  Here are the skipped tests:

``` scheme
(invoke "python" "-m" "pytest"
                     "-k" (string-join
                           (list
                            ;; These tests return "non-zero exit status 1".
                            "not test_default_headless_spawn_options"
                            "not test_default_headless_spawn_options_with_shape"
                            "not test_headless_spawn_options_wo_run_time"
                            ;; This test depends on networking.
                            "not test_web_options"
                            ;; This test fails because of the warning "System open
                            ;; file limit '1024' is below minimum setting '10000'".
                            "not test_skip_logging") " and "))
```

With this small subset of skipped tests, the test suite succeeds. Perhaps the non-network failures could be worth looking into.  They could be due to assumptions made about the host system not holding true in the minimal build container. Otherwise, feel free to close it.

Thank you!

**Comment by Apteryks** [comment]
FYI, Locust is now in packaged in Guix: https://git.savannah.gnu.org/cgit/guix.git/commit/?id=5795f566fae85023c6be86fe62388c29e6ac5c51.

**Comment by cyberw** [comment]
Cool! Thanks!
