### ISSUE TITLE
on_stop method not work, tuple index out of range

### ISSUE THREAD

**Issue by mm25712423** [locustio/locust#1699]
I think the problem is the request/response timeout. But it does not show the assertion failed. And it needs to be shut down normally

### Describe the bug
* Set Locust users number: 20
* Set spawn rate: 10
* Set run time: 90 secs

Problems: 
* Some users did not call the on_stop method
* The task method is still called after on_stop called
* Exhausted my time limit (90 seconds)

### Expected behavior
All users call on_stop and shutdown locust.

### Actual behavior

I tried to interrupt the process because it never stops and it shows:
```shell
[2021-02-05 02:45:09,267] e34866ebd6ad/INFO/locust.main: Running teardowns...
[2021-02-05 02:45:09,267] e34866ebd6ad/INFO/locust.main: Shutting down (exit code 1), bye.
[2021-02-05 02:45:09,267] e34866ebd6ad/INFO/locust.main: Cleaning up runner...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/locust/main.py", line 426, in main
    main_greenlet.join()
  File "/usr/local/lib/python3.8/site-packages/gevent/pool.py", line 430, in join
    result = self._empty_event.wait(timeout=timeout)
  File "src/gevent/event.py", line 163, in gevent._gevent_cevent.Event.wait
  File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/locust", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/locust/main.py", line 433, in main
    shutdown()
  File "/usr/local/lib/python3.8/site-packages/locust/main.py", line 408, in shutdown
    runner.quit()
  File "/usr/local/lib/python3.8/site-packages/locust/runners.py", line 362, in quit
    self.stop()
  File "/usr/local/lib/python3.8/site-packages/locust/runners.py", line 413, in stop
    super().stop()
  File "/usr/local/lib/python3.8/site-packages/locust/runners.py", line 354, in stop
    self.stop_users(self.user_count)
  File "/usr/local/lib/python3.8/site-packages/locust/runners.py", line 223, in stop_users
    user = g.args[0]
IndexError: tuple index out of range
```

### Steps to reproduce
1. Inherit HttpUser class
2. on_start -> Login user and setup
3. on_stop -> Delete user and teardown
4. task -> do something will be take much time

### Environment

- OS:
- Docker version: 19.03.14
- Locust version: 1.4.3
- Locust command line that you ran: 
`docker run -it --rm -v /home/users/workspace/tests/locust/:/mnt/locust locustio/locust:1.4.3 -f /mnt/locust/load_test.py -u 20-r 10 -t 90  -headless`

**Comment by cyberw** [comment]
Please post your locustfile

**Comment by mm25712423** [comment]
The locustfile is here

```python
import logging
import sys

import requests as client
from locust import HttpUser, SequentialTaskSet, between, events, task

USER_CREDENTIALS = [
    ("LocustPerformanceUser5", "5678901"),
    ("LocustPerformanceUser4", "456789"),
    ("LocustPerformanceUser3", "345678"),
    ("LocustPerformanceUser2", "234567"),
    ("LocustPerformanceUser1", "123456")
]


CREDENTIALS = USER_CREDENTIALS
PROJECTS_DICT = {}
HOST = 'http://localhost:8080'


@events.test_start.add_listener
def on_test_start(**kwargs):
    # admin login
    r = client.post(HOST+"/api/auth/login", {"username": "admin", "password": "admin"})
    assert r.status_code == 200
    r = r.json()
    admin_headers = {'Authorization': 'Bearer {}'.format(r['access_token'])}
    # create normal users
    for u in USER_CREDENTIALS:
        username, password = u
        r = client.post(HOST+"/api/users", {
            'username': username, 'password': password, 'plan': 1
        }, headers=admin_headers)
        assert r.status_code == 200

    # users create own projects
    for u in USER_CREDENTIALS:
        username, password = u
        r = client.post(HOST+"/api/auth/login", {
            'username': username, 'password': password
        })
        assert r.status_code == 200
        r = r.json()
        headers = {'Authorization': 'Bearer {}'.format(r['access_token'])}
        r = client.post(HOST+"/api/projects", {
            'name': 'locust_test'
        }, headers=headers)
        assert r.status_code == 200
        r = r.json()
        PROJECTS_DICT[username] = r['id']


@events.test_stop.add_listener
def on_test_stop(**kwargs):
    # admin login
    r = client.post(HOST+"/api/auth/login", {"username": "admin", "password": "admin"})
    assert r.status_code == 200
    r = r.json()
    admin_headers = {'Authorization': 'Bearer {}'.format(r['access_token'])}
    # delete all projects and users
    for user in PROJECTS_DICT:
        r = client.delete(HOST+"/api/projects/"+PROJECTS_DICT[user], headers=admin_headers)
        assert r.status_code == 200
        r = client.delete(HOST+"/api/users/"+user, headers=admin_headers)
        assert r.status_code == 200


class LoginWithUniqueUsersSteps(SequentialTaskSet):

    username = ""
    password = ""
    headers = ""

    def on_start(self):
        if len(USER_CREDENTIALS) > 0:
            self.username, self.password = CREDENTIALS.pop()
            self.login()

    def login(self):
        r = self.client.post("/api/auth/login", {
            'username': self.username, 'password': self.password
        })
        r = r.json()
        self.headers = {'Authorization': 'Bearer {}'.format(r['access_token'])}

    @task
    def create_cpu_lab(self):
        proj_id = PROJECTS_DICT[self.username]
        r = self.client.post("/api/labs", {
            'project_uuid': proj_id, 'name': 'new_lab'
        }, headers=self.headers)
        r = r.json()
        self.lab_id = r['id']


class LoggedInUser(HttpUser):
    wait_time = between(0.5, 2)
    host = HOST
    tasks = [LoginWithUniqueUsersSteps]

    @task
    def index_page(self):
        pass
```

**Comment by cyberw** [comment]
Hm... maybe there is a bug with SequentialTaskSets.

But I get a little confused when you say:

`Some users did not call the on_stop method`

What do you mean? I dont see any on_stop method on your User or SequentialTaskSet? As for test_stop, that is only triggered once per run, not once per User.

**Comment by cyberw** [comment]
Whoa, and your command looks very strange.

`docker run -it --rm -v /home/users/workspace/tests/locust/:/mnt/locust locustio/locust:1.4.3 -f /mnt/locust/load_test.py -u 20-r 10 -t 90 -headless`

you're missing a space, and it is `--headless` with two dashes. How did that even start?

**Comment by mm25712423** [comment]
Sorry, my fault.
I found an error in my locust file. Fix it and done
The command syntax error is because I typed it in the github web application instead of copying and pasting it :P.
