### ISSUE TITLE
Python3.8 logging issue

### ISSUE THREAD

**Issue by gwander** [locustio/locust#1720]
I ran into this error with python 3.8 and 3.9, python 3.7 works
```
Traceback (most recent call last):
  File "/usr/local/bin/locust", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/locust/main.py", line 282, in main
    logger.info(
  File "/usr/lib/python3.8/logging/__init__.py", line 1434, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1565, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given
```

**Comment by cyberw** [comment]
Hi! I'm not sure what this is about, must be something more than just running in python 3.8...
