### ISSUE TITLE
Adding TLS cert causes Errors in debug log, using container image

### ISSUE THREAD

**Issue by brwilkinson** [locustio/locust#1747]
### Describe the bug
I added a TLS cert and that seems to be working correctly.

### Expected behavior

However I am seeing the following errors logged on the console

### Actual behavior

```log
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 233, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 797, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 667, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)
2021-04-14T01:20:52Z <Greenlet at 0x7f7e54abfe10: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7f7e547790a)> failed with SSLEOFError
```

### Steps to reproduce

I configured the following ENV vars

```json
              {
                "Name": "LOCUST_TLS_KEY",
                "value": "/home/locust/locust/mycert-wildcard.key"
              },
              {
                "Name": "LOCUST_TLS_CERT",
                "value": "/home/locust/locust/mycert-wildcard.crt"
              }
```

### Environment

I generated the certs with:   OpenSSL 1.1.1d  10 Sep 2019 

- OS:
"image": "locustio/locust:1.4.4"

**Comment by cyberw** [comment]
Sorry, I dont have any knowledge of how this works. But it looks like a general gevent issue, more than a locust specific one. Perhaps you can try googling in that context/asking in that community?

**Comment by brwilkinson** [comment]
closing based on 'needs time to investigate' and not related to locustio project directly.
