### ISSUE TITLE
Can't start Locust on localhost - getting an OSError

### ISSUE THREAD

**Issue by anthammas** [locustio/locust#1770]
### Describe the bug

I am trying to run locust with the command `locust -f locustfile.py`. My locustfile looks as below
```

    from locust import HttpUser, TaskSet, task
    import urllib.parse
    from locust.env import Environment
    import json
    import urllib3
    from locust.contrib.fasthttp import FastHttpUser
    
    global_header = None
    class RecommenderTasks(TaskSet):
        def __init__(self, parent):
            super().__init__(parent)
            self.global_header = None
            self.cold_start_url = "https://my-web-site"
    
        def on_start(self):
            urllib3.disable_warnings()
            self.global_header = self.login()
            
        def login(self):
            call_url = urllib.parse.urljoin(self.cold_start_url, "/oauth/token")
            headers = {'Authorization': 'Basic (my-token)=='}
            response = self.client.post(call_url, {'grant_type': 'client_credentials'}, headers=headers, verify=False)        
            
            access_token = json.loads(response.text.encode('utf8'))['access_token']
            headers = {'Authorization': 'Bearer ' + access_token}
            return headers
        
        @task
        def test_recommender_multiple_platforms(self):
            
            params = {'rec_id': str(0)}
            response = self.client.request("GET", '/recommendations',
                                    params=params,
                                    headers=self.global_header,
                                    verify=False)
            print(response)
    
    class RecommenderUser(HttpUser):
        tasks = [RecommenderTasks]
        min_wait = 0
        max_wait = 0
    
        host = "https://my-web-site"
```

### Expected behavior

I should be able to start the locust service

### Actual behavior

I am getting the following error

```
[2021-05-31 20:25:34,146] d6ad3fb4f0cf/INFO/locust.main: Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)
[2021-05-31 20:25:34,156] d6ad3fb4f0cf/INFO/locust.main: Starting Locust 1.5.3
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/site-packages/locust/web.py", line 339, in start_server
    self.server.serve_forever()
  File "/usr/local/lib/python3.8/site-packages/gevent/baseserver.py", line 398, in serve_forever
    self.start()
  File "/usr/local/lib/python3.8/site-packages/gevent/baseserver.py", line 336, in start
    self.init_socket()
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 1545, in init_socket
    StreamServer.init_socket(self)
  File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 180, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 192, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 284, in _tcp_listener
    sock = GeventSocket(family=family)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socket3.py", line 133, in __init__
    self._sock = self._gevent_sock_class(family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
2021-05-31T20:25:34Z <Greenlet at 0x7f11128f47b0: <bound method WebUI.start_server of <locust.web.WebUI object at 0x7f1112877e50>>> failed with OSError
```

May I know what would be the cause of such an exception?

### Environment

- OS: Windows
- Python version: 3.8
- Locust version: latest
- Locust command line that you ran: locust -f locustfile.py
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Could be some ipv6 issue? Are you really on windows (and not on WSL or something)? Those file locations look like unix paths :)

Try adding `--web-host localhost` to bind only to that interface (no idea if that will help, but maybe...)

**Comment by anthammas** [comment]
Perplexed as I am, a system restart resolved the issue. Closing it ! Thanks :)
