### ISSUE TITLE
Locust 1.5.3 greenlet AttributeError: 'RetriesExceeded' object has no attribute 'kwargs_text'

### ISSUE THREAD

**Issue by ecc256** [locustio/locust#1792]
Guys,
I've upgraded to Anaconda3-2021.05, recreated locust env and start getting the error below.
Is it something expected or do I need to do anything in my code to fix it?

```
with self.client.get(url, headers=self.headers, catch_response=True) as response:
	if response.status_code != self.status_code:
		print(f'{self.id}: got {response.status_code}, expected {self.status_code} for {url}')

```
`Python 3.9.5`
```
[2021-06-20 11:02:16,107] WSAMZN-ABCD1234/INFO/locust.main: Run time limit set to 7200 seconds
[2021-06-20 11:02:16,107] WSAMZN-ABCD1234/INFO/locust.main: Starting Locust 1.5.3
[2021-06-20 11:02:16,122] WSAMZN-ABCD1234/INFO/locust.runners: Spawning 1 users at the rate 1 users/s (0 users already running)...
[2021-06-20 11:02:16,122] WSAMZN-ABCD1234/INFO/locust.runners: All users spawned: User: 1 (1 total running)
[2021-06-20 11:02:16,122] WSAMZN-ABCD1234/INFO/locust.runners: Resetting stats

0: got 0, expected 200 for http://acb.def.com/viewitems/categories
[2021-06-20 11:04:04,765] WSAMZN-ABCD1234/ERROR/root: Uncaught exception in event handler:
Traceback (most recent call last):
  File "c:\users\user\anaconda3\envs\locust395\lib\site-packages\locust\event.py", line 40, in fire
    handler(**kwargs)
  File "c:\users\user\anaconda3\envs\locust395\lib\site-packages\locust\runners.py", line 79, in on_request_failure
    self.stats.log_error(request_type, name, exception)
  File "c:\users\user\anaconda3\envs\locust395\lib\site-packages\locust\stats.py", line 143, in log_error
    key = StatsError.create_key(method, name, error)
  File "c:\users\user\anaconda3\envs\locust395\lib\site-packages\locust\stats.py", line 640, in create_key
    key = "%s.%s.%r" % (method, name, StatsError.parse_error(error))
  File "c:\users\user\anaconda3\envs\locust395\lib\site-packages\locust\stats.py", line 626, in parse_error
    string_error = repr(error)
  File "c:\users\user\anaconda3\envs\locust395\lib\site-packages\geventhttpclient\useragent.py", line 48, in __repr__
    if self.kwargs_text:
AttributeError: 'RetriesExceeded' object has no attribute 'kwargs_text'
```
```
(locust395)>conda list
# packages in environment at c:\users\user\Anaconda3\envs\locust395:
#
# Name                    Version                   Build  Channel
ca-certificates           2021.5.25            haa95532_1
certifi                   2021.5.30        py39haa95532_0
cffi                      1.14.5                   pypi_0    pypi
chardet                   4.0.0                    pypi_0    pypi
click                     8.0.1                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
configargparse            1.4.1                    pypi_0    pypi
flask                     1.1.2                    pypi_0    pypi
flask-basicauth           0.2.0                    pypi_0    pypi
gevent                    21.1.2                   pypi_0    pypi
geventhttpclient          1.4.4                    pypi_0    pypi
greenlet                  1.1.0                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
itsdangerous              2.0.1                    pypi_0    pypi
jinja2                    3.0.1                    pypi_0    pypi
locust                    1.5.3                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
msgpack                   1.0.2                    pypi_0    pypi
openssl                   1.1.1k               h2bbff1b_0
pip                       21.1.2           py39haa95532_0
psutil                    5.8.0                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pyodbc                    4.0.30                   pypi_0    pypi
python                    3.9.5                h6244533_3
pywin32                   228              py39he774522_0
pyzmq                     22.1.0                   pypi_0    pypi
requests                  2.25.1                   pypi_0    pypi
setuptools                52.0.0           py39haa95532_0
sqlite                    3.35.4               h2bbff1b_0
tzdata                    2020f                h52ac0ba_0
urllib3                   1.26.5                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2              py39h2bbff1b_0
zope-event                4.5.0                    pypi_0    pypi
zope-interface            5.4.0                    pypi_0    pypi

```

**Comment by cyberw** [comment]
Your code looks all good. Possibly something related to #1750 , or something conda-specific. 

It is hard to debug from here. If you do find the issue then please make a PR.

**Comment by ecc256** [comment]
Lars,
It’s not a big deal, rather a little annoyance.
If you want, I can rerun it on Python virtualenv...
And if you have an idea what I can add to my code to pinpoint it further - I’ll do it gladly! :)
