### ISSUE TITLE
KeyboardInterrupt does not gracefully exit custom load shape

### ISSUE THREAD

**Issue by ghost** [locustio/locust#1910]
### Describe the bug
KeyboardInterrupt does not gracefully exit custom load shape.

### Expected behavior
A report should be generated after Ctrl-C, like with a normal test case.

### Actual behavior
The program crashes:

```
[2021-10-21 10:07:23,218] user-vm/INFO/locust.runners: Shape worker starting
[2021-10-21 10:07:23,218] user-vm/INFO/locust.runners: Shape test updating to 10 users at 10.00 spawn rate
[2021-10-21 10:07:23,218] user-vm/INFO/locust.runners: Ramping to 10 users at a rate of 10.00 per second
[2021-10-21 10:07:23,219] user-vm/INFO/locust.runners: All users spawned: {"WebsiteUser": 10} (10 total users)
^CKeyboardInterrupt
2021-10-21T08:07:24Z
Traceback (most recent call last):
  File "/home/user/.local/bin/locust", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/locust/main.py", line 383, in main
    start_automatic_run()
  File "/home/user/.local/lib/python3.7/site-packages/locust/main.py", line 370, in start_automatic_run
    environment.runner.shape_greenlet.join()
  File "src/gevent/greenlet.py", line 831, in gevent._gevent_cgreenlet.Greenlet.join
  File "src/gevent/greenlet.py", line 857, in gevent._gevent_cgreenlet.Greenlet.join
  File "src/gevent/greenlet.py", line 846, in gevent._gevent_cgreenlet.Greenlet.join
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
KeyboardInterrupt

```

### Steps to reproduce
Use [this example](https://github.com/locustio/locust/blob/master/examples/custom_shape/step_load.py) from this very repo, launched as `locust --headless -f step_load.py --host https://localhost`:

### Environment

- OS: Linux
- Python version: 3.7.3
- Locust version: 2.4.1
- Locust command line that you ran:`locust --headless -f step_load.py --host https://localhost`
- Locust file contents (anonymized if necessary):  https://github.com/locustio/locust/blob/master/examples/custom_shape/step_load.py

**Comment by JevonCowell** [comment]
I believe this issue still persists (using 2.14.2). From the error trace we see that it fails in
`environment.runner.shape_greenlet.join()`

It's dirty, but we could catch it like this to let it end gracefully: 

```
# start the test
            if environment.shape_class:
                if options.run_time:
                    sys.stderr.write("It makes no sense to combine --run-time and LoadShapes. Bailing out.\n")
                    sys.exit(1)
                try:
                    logger.info("Modified Locust Main is running")
                    environment.runner.start_shape()
                    environment.runner.shape_greenlet.join()
                except KeyboardInterrupt:
                    logging.info("Exiting due to CTRL+C to interruption")
                finally:
                    stop_and_optionally_quit()
```

Thoughts? Locust's inability to gracefully exit means `@events.test_stop.add_listener` doesn't work.

**Comment by cyberw** [comment]
LGTM, PR very welcome. PR with unit test even more so :) 

I'd skip the "modified locust main is running" logging though (unclear what that even means)

**Comment by JevonCowell** [comment]
https://github.com/locustio/locust/pull/2375

**Comment by JevonCowell** [comment]
Sorry to reopen this issue, I was wondering what the release cadence of locust was or something I have to do on my end to get the next version released with these changes

**Comment by cyberw** [comment]
There’s no particular cadence and the current master version has a feature that I might not want to release after all :) but I can probably squeeze it in this weekend. But you can always use the latest PR merge using `pip install —pre`
