### ISSUE TITLE
Syntax Error 

### ISSUE THREAD

**Issue by mositafan10** [locustio/locust#2043]
There is a problem with locust and Anaconda.
I download locust package from anaconda.org and then move it to offline server. There i install the package with conda and installment finish successfully but when i insert in cmd an exception throw:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\Scripts\locust-script.py", line 5, in
from locust.main import main
File "C:\ProgramData\Anaconda2\lib\site-packages\locust_init_.py", line 14, in
from .user.sequential_taskset import SequentialTaskSet
File "C:\ProgramData\Anaconda2\lib\site-packages\gevent\builtins.py", line 96, in import
result = import(*args, **kwargs)
File "C:\ProgramData\Anaconda2\lib\site-packages\locust\user_init.py", line 1, in
from .task import task, tag, TaskSet
File "C:\ProgramData\Anaconda2\lib\site-packages\gevent\builtins.py", line 96, in import
result = _import(*args, **kwargs)
File "C:\ProgramData\Anaconda2\lib\site-packages\locust\user\task.py", line 24
def task(weight: TaskT) -> TaskT:
^
SyntaxError: invalid syntax

Python version is 3.6.5 and locust 2.8.3

What is the problem ?

**Comment by cyberw** [comment]
Something with your conda setup? Maybe Anaconda2 is for python 2?
