### ISSUE TITLE
Run in docker: ERROR/locust.runners: RPCError found when receiving from client: ZMQ network broken

### ISSUE THREAD

**Issue by zhangboyi** [locustio/locust#2053]
### Describe the bug

it cann not work when running in docker.

```text
[+] Running 3/0
 ⠿ Container myexample-master-3  Created                                                                                                                                                                           0.0s
 ⠿ Container myexample-worker-2  Created                                                                                                                                                                           0.0s
 ⠿ Container myexample-worker-3  Created                                                                                                                                                                           0.0s
Attaching to myexample-master-3, myexample-worker-2, myexample-worker-3
myexample-master-3  | [2022-03-20 04:43:43,888] 374ef93331c9/INFO/locust.main: Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)
myexample-worker-3  | 0
myexample-worker-3  | I'm on a worker or standalone node
myexample-worker-2  | 0
myexample-worker-2  | I'm on a worker or standalone node
myexample-worker-3  | [2022-03-20 04:43:43,890] 55e0acab805b/INFO/locust.main: Starting Locust 2.8.4
myexample-worker-2  | [2022-03-20 04:43:43,890] 37541a5124ca/INFO/locust.main: Starting Locust 2.8.4
myexample-master-3  | 0
myexample-master-3  | I'm on master node
myexample-master-3  | [2022-03-20 04:43:43,901] 374ef93331c9/INFO/locust.main: Starting Locust 2.8.4
myexample-master-3  | [2022-03-20 04:43:51,069] 374ef93331c9/WARNING/locust.runners: You can't start a distributed test before at least one worker processes has connected
myexample-worker-2  | [2022-03-20 04:56:13,710] 37541a5124ca/INFO/locust.util.exception_handler: Exception found on retry 1: -- retry after 1s
myexample-worker-3  | [2022-03-20 04:56:13,710] 55e0acab805b/INFO/locust.util.exception_handler: Exception found on retry 1: -- retry after 1s
myexample-worker-3  | [2022-03-20 04:56:13,710] 55e0acab805b/ERROR/locust.util.exception_handler: ZMQ sent failure
myexample-worker-3  | Traceback (most recent call last):
myexample-worker-3  |   File "/opt/venv/lib/python3.9/site-packages/locust/rpc/zmqrpc.py", line 20, in send
myexample-worker-3  |     self.socket.send(msg.serialize(), zmq.NOBLOCK)
myexample-worker-3  |   File "/opt/venv/lib/python3.9/site-packages/zmq/green/core.py", line 216, in send
myexample-worker-3  |     msg = super(_Socket, self).send(data, flags, copy, track, **kwargs)
myexample-worker-3  |   File "/opt/venv/lib/python3.9/site-packages/zmq/sugar/socket.py", line 547, in send
myexample-worker-3  |     return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
myexample-worker-3  |   File "zmq/backend/cython/socket.pyx", line 718, in zmq.backend.cython.socket.Socket.send
myexample-worker-3  |   File "zmq/backend/cython/socket.pyx", line 765, in zmq.backend.cython.socket.Socket.send
myexample-worker-3  |   File "zmq/backend/cython/socket.pyx", line 247, in zmq.backend.cython.socket._send_copy
myexample-worker-3  |   File "zmq/backend/cython/socket.pyx", line 242, in zmq.backend.cython.socket._send_copy
myexample-worker-3  |   File "zmq/backend/cython/checkrc.pxd", line 22, in zmq.backend.cython.checkrc._check_rc
myexample-worker-3  | zmq.error.Again: Resource temporarily unavailable
myexample-worker-3  | 


```

### Environment

- OS:
- Python version:python3.8
- Locust version: 2.8.4
- Locust command line that you ran: docker-compose -f run_by_locust.yaml up --scale worker=2
- Locust file contents (anonymized if necessary):
docker-compose.yml
```yaml
version: '3'

services:
  master:
    image: locustio/locust:latest
    ports:
      - 8089:8089
    volumes:
      - ./:/myexample
    command: -f /myexample/locustfile.py WebsiteUser --master

  worker:
    image: locustio/locust:latest
    links:
      - master
    volumes:
      - ./:/myexample
    command: -f /myexample/locustfile.py WebsiteUser --worker --master-host=127.0.0.1
```

**Comment by cyberw** [comment]
No idea whats going on but is it possible you had some old containers that are interfering? It is suspicious that the master would be named master-**3**

**Comment by zhangboyi** [comment]
@[cyberw](https://github.com/cyberw) it cannot work. do you give me advise?

**Comment by cyberw** [comment]
Sorry, I have no way to know what is wrong, you need to do more digging (currently running docker containers investigate if a process is bound to that port etc)
