### ISSUE TITLE
Add test support for Arm64 

### ISSUE THREAD

**Issue by odidev** [locustio/locust#2076]
Hi Team, 

I tried testing locust package on **Arm64** architectures but it is generating `2 errors with 5 failed, 1 skipped` from total of **445 test cases** for the **tox** test command with the assertion errors locally: 

``` 

====================================================================== 

FAIL: test_webserver (locust.test.test_main.StandaloneIntegrationTests) 

---------------------------------------------------------------------- 

Traceback (most recent call last): 

  File "/locust/locust/test/test_main.py", line 310, in test_webserver 

    self.assertIn("Starting web interface at", stderr) 

AssertionError: 'Starting web interface at' not found in ''  

---------------------------------------------------------------------- 

``` 

While on **amd64**, I am getting `Ran 445 tests OK (skipped=1)`.  

Also we have raised a PR for docker images where we got a suggestion to change the **version of flask** refer [comment](https://github.com/locustio/locust/pull/1889#issuecomment-936337793) in order to **test**. 

**PR link:** https://github.com/locustio/locust/pull/1889 

About a month ago when I tried with GHA it was `Ran 440 tests FAILED (failures=15, errors=9, skipped=1)` for arm64 with different assertion errors, currently **the tox command fails** for arm64.  

As per the above [comment](https://github.com/locustio/locust/pull/1889#issuecomment-936337793) suggestion there is still no proper support for the arm on GH so we can't just add it to the matrix build, so I also tried with TravisCI where again the tox command fails for arm64.

[Cyberw](https://github.com/cyberw) Could you please share your feedback regarding this and suggest what can be done to test it over ARM64 server? 

Thanks in advance.

**Comment by cyberw** [comment]
Hi! I dont really have much to add. If you print stuff in the test case (like the process return code, any output on stdout) before asserting maybe you will get a hint on what went wrong.

**Comment by odidev** [comment]
@cyberw Thanks for the quick reply. 
 Currently, the tox command fails for arm64 with below error:
```
+ python3 -m tox -e py38
py38 create: /ws/.tox/py38
py38 installdeps: codecov, mock, retry, pyquery, cryptography
py38 installed: certifi==[2021](https://github.com/bhumikapahariapuresoftware/locust/runs/6082019231?check_suite_focus=true#step:4:2021).10.8,cffi==1.15.0,charset-normalizer==2.0.12,codecov==2.1.12,coverage==6.3.2,cryptography==36.0.2,cssselect==1.1.0,decorator==5.1.1,idna==3.3,lxml==4.8.0,mock==4.0.3,py==1.11.0,pycparser==2.21,pyquery==1.4.3,requests==2.27.1,retry==0.9.2,urllib3==1.26.9
py38 run-test-pre: PYTHONHASHSEED='3857424216'
py38 run-test: commands[0] | python3 -m pip install .
Processing /ws
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      Traceback (most recent call last):
        File "/ws/.tox/py38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/ws/.tox/py38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/ws/.tox/py38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-wih6551e/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-wih6551e/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-wih6551e/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 4, in <module>
          setuptools.setup()
        File "/tmp/pip-build-env-wih6551e/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-wih6551e/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-wih6551e/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 462, in __init__
          _Distribution.__init__(
        File "/tmp/pip-build-env-wih6551e/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-wih6551e/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 886, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-wih6551e/overlay/lib/python3.8/site-packages/setuptools_scm/integration.py", line 104, in infer_version
          _assign_version(dist, config)
        File "/tmp/pip-build-env-wih6551e/overlay/lib/python3.8/site-packages/setuptools_scm/integration.py", line 51, in _assign_version
          _version_missing(config)
        File "/tmp/pip-build-env-wih6551e/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 106, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /ws.
      
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: InvocationError for command /ws/.tox/py38/bin/python3 -m pip install . (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py38: commands failed
Error: Process completed with exit code 1.
```
Can you pls share some pointers on this??

**Comment by cyberw** [comment]
Seems to be an issue with setuptools-scm. As stated in the error message you need to have a complete git checkout - maybe that is the issue?

For example, in GH actions we need to specify BUILDKIT_CONTEXT_KEEP_GIT_DIR=1 to ensure the .git folder is propagated into docker.

**Comment by odidev** [comment]
@cyberw I checked with the above mentioned suggestions but it didn't change the result of tox command failing both on GHA and locally.

**Comment by cyberw** [comment]
Can you make it run just `git status` in /ws and see what it says?
