### ISSUE TITLE
Flask 2.2.0 Update breaks request_stats_full_history_csv in web.py

### ISSUE THREAD

**Issue by mikenester** [locustio/locust#2147]
### Describe the bug
Flask released version 2.2.0 yesterday, August 1st, and it appears to have removed the `cache_timeout` kwarg from `send_file`: [diff link](https://github.com/pallets/flask/compare/2.1.3...2.2.0#diff-1f51c8ded4d4ff7e13badab599ef22436c529c2b5f9c25dc6250c1f9fd985440L507). This causes the test `test_request_stats_full_history_csv` to fail since `request_stats_full_history_csv` [uses that kwarg](https://github.com/locustio/locust/blob/master/locust/web.py#L247)

When running `tox -e py39` locally, this issue doesn't occur, but I noticed it's installing Flask version 2.1.2. That test fails when ran via Github Actions, on my forked (and up-to-date) [master branch of Locust](https://github.com/mikenester/locust/actions/runs/2783869348)

I repeated the steps manually

### Expected behavior
`test_request_stats_full_history_csv` method and the **stats/requests_full_history/csv** endpoint can be used with Flask 2.2.0

### Actual behavior
Internal Server Error

### Steps to reproduce

1. Run `python3 -m pip install flask==2.2.0`
2. Run `locust -f locustfiles/locustfile1.py --csv web_test --csv-full-history`
3. Run the test against any host and stop if after it a cycle or two
4. Navigate to http://localhost:8089/stats/requests_full_history/csv

Internal server error is shown with the stack trace at the bottom of this write up.
This issue does not occur with flask 2.1.2

### Environment

- OS: macOS Monterey w/ M1
- Python version: 3.9.13
- Locust version: 2.10.1 (up-to-date master branch)
- Locust command line that you ran: `locust -f locustfiles/locustfile1.py --csv web_test --csv-full-history`
- Locust file contents (anonymized if necessary): n/a

#### Error Stack Trace
```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/gevent/pywsgi.py", line 999, in handle_one_response
    self.run_application()
  File "/opt/homebrew/lib/python3.9/site-packages/gevent/pywsgi.py", line 945, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 2486, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 2466, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/homebrew/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 2463, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1760, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/homebrew/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1758, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1734, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/homebrew/lib/python3.9/site-packages/locust/web.py", line 433, in wrapper
    return view_func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/locust/web.py", line 241, in request_stats_full_history_csv
    return send_file(
TypeError: send_file() got an unexpected keyword argument 'cache_timeout'
2022-08-02T22:19:16Z {'REMOTE_ADDR': '::1', 'REMOTE_PORT': '53516', 'HTTP_HOST': 'localhost:8089', (hidden keys: 34)} failed with TypeError
```

**Comment by mikenester** [comment]
After writing that up i realized it would have been easier to just open a PR with a fix. So I'm gonna test out removing that kwarg and will do so
