### ISSUE TITLE
ImportError: cannot import name 'OrderedDict' from 'typing'

### ISSUE THREAD

**Issue by jinghaifeng1** [locustio/locust#2223]
### Describe the bug
pytnon : 3.7.0
locust: 2.12.1   2.10.1

When I started locust with this configuration, I get an error

Traceback (most recent call last):
  File "d:\jhf\software\python\python370\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\jhf\software\python\python370\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\jhf\software\python\python370\Scripts\locust.exe\__main__.py", line 5, in <module>
  File "d:\jhf\software\python\python370\lib\site-packages\locust\__init__.py", line 18, in <module>
    from .contrib.fasthttp import FastHttpUser
  File "d:\jhf\software\python\python370\lib\site-packages\locust\contrib\fasthttp.py", line 24, in <module>
    from locust.env import Environment
  File "d:\jhf\software\python\python370\lib\site-packages\locust\env.py", line 15, in <module>
    from .stats import RequestStats, StatsCSV
  File "d:\jhf\software\python\python370\lib\site-packages\locust\stats.py", line 15, in <module>
    from typing import (
ImportError: cannot import name 'OrderedDict' from 'typing' (d:\jhf\software\python\python370\lib\typing.py)

### Suggestion for repairing
in   python370\lib\site-packages\locust\stats.py 

del  import   OrderedDict as OrderedDictType, 

replace  326 line   "OrderedDictType"   to  "OrderedDict"

### Environment

- OS: windwos 10
- Python version: 3.7.0
- Locust version: (please dont file issues for anything but the most recent release or prerelease builds) 2.12.1    2.10.1
- Locust command line that you ran: locust.exe --master -f collect.py --web-host="XXXXXXXXX"

**Comment by cyberw** [comment]
I think Python 3.7.0 is broken, please update to at least 3.7.2 (but preferably latest 3.7 release or newer)

**Comment by jinghaifeng1** [comment]
> I think Python 3.7.0 is broken, please update to at least 3.7.2 (but preferably latest 3.7 release or newer)

OK

**Comment by Mauricio566** [comment]
What @cyberw  says is true, try version 3.7.9, it worked for me. and thank you very much @cyberw
