### ISSUE TITLE
locust 2.13.0 failed to run

### ISSUE THREAD

**Issue by willysr** [locustio/locust#2263]
### Describe the bug
I tried to build locust 2.13.0 on slackware-current but it failed to run with the following error message

```
locust 
Traceback (most recent call last):
  File "/usr/bin/locust", line 33, in <module>
    sys.exit(load_entry_point('locust==2.13.0', 'console_scripts', 'locust')())
  File "/usr/bin/locust", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib64/python3.9/site-packages/locust/__init__.py", line 18, in <module>
    from .contrib.fasthttp import FastHttpUser
  File "/usr/lib64/python3.9/site-packages/locust/contrib/fasthttp.py", line 24, in <module>
    from locust.env import Environment
  File "/usr/lib64/python3.9/site-packages/locust/env.py", line 16, in <module>
    from .runners import Runner, LocalRunner, MasterRunner, WorkerRunner
  File "/usr/lib64/python3.9/site-packages/locust/runners.py", line 43, in <module>
    import psutil
  File "/usr/lib64/python3.9/site-packages/psutil/__init__.py", line 102, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib64/python3.9/site-packages/psutil/_pslinux.py", line 87, in <module>
    PAGESIZE = cext_posix.getpagesize()
AttributeError: module 'psutil._psutil_posix' has no attribute 'getpagesize'
```

i have psutil 5.9.4, which is the latest version 

### Expected behavior
locust run normally

### Actual behavior
locust failed to run

### Steps to reproduce
build all dependencies of locust and locust 2.13.0

### Environment

- OS: Slackware-Current
- Python version: 3.9.15
- Locust version: 2.13.0
- Locust command line that you ran: locust

**Comment by cyberw** [comment]
Huh. That's strange. Can you try an older version of psutil just in case? Otherwise my guess is that your installation is corrupt somehow...

**Comment by willysr** [comment]
i think it's because of this commit 
https://github.com/giampaolo/psutil/pull/1891/commits/25a2ab60d157a2369ec32110544470e332e8ab80

**Comment by willysr** [comment]
@cyberw which version of psutil did you use currently now?

**Comment by cyberw** [comment]
I have been using 5.9.1, but now updated to latest (5.9.4) now and both were fine.

**Comment by willysr** [comment]
that's strange. I'm sure that my is ok since i tested other code and it's working just fine

**Comment by cyberw** [comment]
strange...

**Comment by cyberw** [comment]
You wouldnt happen to have a file called psutil.py or similar in your current directory?
