### ISSUE TITLE
Cannot run on MacBook Air M2

### ISSUE THREAD

**Issue by efmoyano** [locustio/locust#2292]
### Describe the bug
Just installed locust in 2022 MacBook Air M2 and got this error
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/locust", line 5, in <module>
    from locust.main import main
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/locust/__init__.py", line 18, in <module>
    from .contrib.fasthttp import FastHttpUser
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/locust/contrib/fasthttp.py", line 19, in <module>
    from geventhttpclient._parser import HTTPParseError
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/geventhttpclient/__init__.py", line 5, in <module>
    from geventhttpclient.client import HTTPClient
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/geventhttpclient/client.py", line 10, in <module>
    from geventhttpclient.response import HTTPConnectionClosed
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/geventhttpclient/response.py", line 3, in <module>
    from geventhttpclient._parser import HTTPResponseParser
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/geventhttpclient/_parser.cpython-311-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/geventhttpclient/_parser.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/geventhttpclient/_parser.cpython-311-darwin.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/geventhttpclient/_parser.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
`

### Expected behavior
Run on current architecture 

### Actual behavior
Crash

### Steps to reproduce
Installed with steps from installation page
`$ pip3 install locust` 

### Environment

- OS: Ventura 13.1
- Python version: 3.11.1
- Locust version: latest
- Locust command line that you ran: locust -V
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Installs just fine for me on M1 MAX, using a pyenv-installed python 3.11.1. Perhaps you have ended up with an x86 Python installed? Try running this, to check:

<img width="641" alt="image" src="https://user-images.githubusercontent.com/1134328/214552187-c48c741a-3200-4aed-a958-7e79786ffcec.png">

**Comment by cyberw** [comment]
Also maybe have a look at https://github.com/locustio/locust/issues/2249
