### ISSUE TITLE
ValueError when missing hatchrate

### ISSUE THREAD

**Issue by pawelmhm** [locustio/locust#237]
Not a big deal, but if you forget to specify hatch_rate in web interface you'll get ugly exception in logs, flask app could check for blank values in form and return some friendly error message to client

```
[2015-01-27 15:16:56,474] pawel-All-Series/ERROR/stderr: Traceback (most recent call last):
[2015-01-27 15:16:56,474] pawel-All-Series/ERROR/stderr: File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 508, in handle_one_response
[2015-01-27 15:16:56,474] pawel-All-Series/ERROR/stderr: self.run_application()
[2015-01-27 15:16:56,474] pawel-All-Series/ERROR/stderr: File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 494, in run_application
[2015-01-27 15:16:56,474] pawel-All-Series/ERROR/stderr: self.result = self.application(self.environ, self.start_response)
[2015-01-27 15:16:56,474] pawel-All-Series/ERROR/stderr: File "/home/pawel/py/flask/flask/app.py", line 1903, in __call__
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: return self.wsgi_app(environ, start_response)
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: File "/home/pawel/py/flask/flask/app.py", line 1887, in wsgi_app
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: response = self.make_response(self.handle_exception(e))
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: File "/home/pawel/py/flask/flask/app.py", line 1465, in handle_exception
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: reraise(exc_type, exc_value, tb)
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: File "/home/pawel/py/flask/flask/app.py", line 1884, in wsgi_app
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: response = self.full_dispatch_request()
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: File "/home/pawel/py/flask/flask/app.py", line 1539, in full_dispatch_request
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: rv = self.handle_user_exception(e)
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: File "/home/pawel/py/flask/flask/app.py", line 1443, in handle_user_exception
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: reraise(exc_type, exc_value, tb)
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: File "/home/pawel/py/flask/flask/app.py", line 1537, in full_dispatch_request
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: rv = self.dispatch_request()
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: File "/home/pawel/py/flask/flask/app.py", line 1523, in dispatch_request
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: return self.view_functions[rule.endpoint](**req.view_args)
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: File "/usr/local/lib/python2.7/dist-packages/locust/web.py", line 50, in swarm
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: hatch_rate = float(request.form["hatch_rate"])
[2015-01-27 15:16:56,555] pawel-All-Series/ERROR/stderr: ValueError: could not convert string to float:
[2015-01-27 15:16:56,559] pawel-All-Series/ERROR/stderr: {'CONTENT_LENGTH': '27',
```

Overall locust is great though.

**Comment by mejibyte** [comment]
I was just hit with this issue. Spent a long time debugging only to realize I had just left hatch rate blank in the form. Showing a friendlier error on the UI would be a great user experience improvement, especially for Locust newcomers.
