### ISSUE TITLE
RuntimeError: can't start new thread inside docker image in Jenkins

### ISSUE THREAD

**Issue by luckhiem** [locustio/locust#2390]
### Describe the bug
RuntimeError: can't start new thread inside docker image in Jenkins

### Actual behavior
RuntimeError: can't start new thread inside docker image in Jenkins
```
[2023-09-01 15:52:27,844] 96840a346a68/ERROR/locust.user.task: can't start new thread
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/locust/user/task.py", line 347, in run
    self.execute_next_task()
  File "/opt/venv/lib/python3.10/site-packages/locust/user/task.py", line 372, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/opt/venv/lib/python3.10/site-packages/locust/user/task.py", line 384, in execute_task
    task(self)
```
### Environment
- Python version: Python 3.10.12
- Docker image: `locustio/locust`
- Locust version: 2.16
- Locust command line that you ran: locust --config=master.conf

```
locustfile = src/tasks/tasks.py
headless = true
host = http://target-system
users = 10
spawn-rate = 2
run-time = 10s
html = load_test_report.html
loglevel = "DEBUG"
```

**Comment by cyberw** [comment]
https://stackoverflow.com/questions/1834919/error-cant-start-new-thread

**Comment by ycchanau** [comment]
Same issue. Switch back to 2.15 is okay

**Comment by cyberw** [comment]
You might want to try 2.18 as there has been a minor fix that might help with setting process limitations. But since this is only a problem in your jenkins I think you'll need to figure it out there...
