### ISSUE TITLE
Misleading log line when starting listener, particularly if running in a IPv4-only environment

### ISSUE THREAD

**Issue by rpetre** [locustio/locust#2407]
### Describe the bug

When starting the web interface, Locust logs "Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)", even though it's actually trying to start on http://:8089 (which if I understand correctly causes a dual-stack socket to be used). This is relevant when running in an environment when IPv6 has been disabled, since the subsequent "OSError: [Errno 97] Address family not supported by protocol" could actually be avoided if it actually used 0.0.0.0 explicitly (can be set via the --web-host option).

### Expected behavior

At the very least, it should use an empty string or '::' instead of 0.0.0.0 if that's what actually gets passed to gevent by default. Ideally the exception could be handled by hinting the use of --web-host for overriding the listening address.

### Actual behavior

```
Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)
Starting Locust 2.15.1
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/opt/venv/lib/python3.10/site-packages/locust/web.py", line 478, in start_server
    self.server.serve_forever()
  File "/opt/venv/lib/python3.10/site-packages/gevent/baseserver.py", line 398, in serve_forever
    self.start()
  File "/opt/venv/lib/python3.10/site-packages/gevent/baseserver.py", line 336, in start
    self.init_socket()
  File "/opt/venv/lib/python3.10/site-packages/gevent/pywsgi.py", line 1545, in init_socket
    StreamServer.init_socket(self)
  File "/opt/venv/lib/python3.10/site-packages/gevent/server.py", line 180, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/opt/venv/lib/python3.10/site-packages/gevent/server.py", line 192, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/opt/venv/lib/python3.10/site-packages/gevent/server.py", line 284, in _tcp_listener
    sock = GeventSocket(family=family)
  File "/opt/venv/lib/python3.10/site-packages/gevent/_socket3.py", line 133, in __init__
    self._sock = self._gevent_sock_class(family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
2023-09-23T19:55:58Z <Greenlet at 0x7f403a3e3b00: <bound method WebUI.start_server of <locust.web.WebUI object at 0x7f403a328dc0>>> failed with OSError
```

After (finally) adding the --web-host 0.0.0.0 commandline option, it ran without issue:
```
Starting web interface at http://0.0.0.0:8089
Starting Locust 2.15.1
```

### Steps to reproduce

I'm not sure what the simplest way to reproduce it, in my case I ran it inside kubernetes on nodes I already knew I disabled IPv6 on (via ipv6.disable=1 in the kernel cmdline). I found several posts on stackoverflow that had a similar issue and seemed to run in some WSL environment, so maybe that could also be a possible case.

### Environment

- OS: Linux kernel 4.19.0-24-amd64 with ipv6 disabled
- Python/Locust version: the locustio/locust:2.15.1 container image from dockerhub, ran via the deliveryhero/locust helm chart , with minimal configuration

**Comment by cyberw** [comment]
The reason we print 0.0.0.0 is to make it a clickable link. Is there a way to make that still work?

**Comment by cyberw** [comment]
Closing, not running on latest version
