### ISSUE TITLE
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 40 from PyObject

### ISSUE THREAD

**Issue by luorq3** [locustio/locust#2539]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Dependency:  gevent-23.9.1  greenlet-3.0.3. locust-2.20.1
System: macOS m1

After I installed Locust with `pip3 install locust`, I can't run command `locust` normally.Detailed ouput:

Traceback (most recent call last):
  File "/Library/anaconda3/envs/delta/bin/locust", line 5, in <module>
    from locust.main import main
  File "/Library/anaconda3/envs/delta/lib/python3.8/site-packages/locust/__init__.py", line 13, in <module>
    from gevent import monkey
  File "/Library/anaconda3/envs/delta/lib/python3.8/site-packages/gevent/__init__.py", line 72, in <module>
    from gevent._hub_local import get_hub
  File "/Library/anaconda3/envs/delta/lib/python3.8/site-packages/gevent/_hub_local.py", line 150, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/Library/anaconda3/envs/delta/lib/python3.8/site-packages/gevent/_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "/Library/anaconda3/envs/delta/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/_hub_local.py", line 1, in init gevent._gevent_c_hub_local
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 40 from PyObject

### Command line

locust -V

### Locustfile contents

```python3
from locust import HttpUser, task

class HelloWorldUser(HttpUser):
    @task
    def hello_world(self):
        self.client.get("https://www.google.com/")
```

### Python version

3.8.5

### Locust version

gevent-23.9.1  greenlet-3.0.3. locust-2.20.1

### Operating system

macOS m1

**Comment by cyberw** [comment]
Hi! Greenlet 3.0.3 was released just a couple weeks ago. Can you try installing greenlet 3.0.2? Or install using `--no-binary gevent`

**Comment by luorq3** [comment]
Hi, I have tried install `greenlet 3.0.2` or reinstall `gevent` with `--no-binary`, this problem still exists.

And if I change a device, `locust -V` works well. 

So maybe it's indeed a anaconda-specific problem.

Thank you!
