### ISSUE TITLE
GRPC deadlock on startup

### ISSUE THREAD

**Issue by zeionara** [locustio/locust#2543]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

What happened: When testing [milvus](https://milvus.io/) cluster with an official [python client](https://github.com/milvus-io/pymilvus) which uses grpc, the tests deadlock on startup. The program hangs after `initializing milvus client...` (see below).
What is expected: The tests are successfully initialized and the tasks are run, the program doesn't hang.

The locust log:

```
[2024-01-11 15:14:05,400] ornn/WARNING/locust.main: System open file limit '1024 is below minimum setting '10000'.
It's not high enough for load testing, and the OS didn't allow locust to increase it by itself.
See https://github.com/locustio/locust/wiki/Installation#increasing-maximum-number-of-open-files-limit for more info.
[2024-01-11 15:14:05,400] ornn/INFO/locust.main: Starting web interface at http://0.0.0.0:8089
[2024-01-11 15:14:05,408] ornn/INFO/locust.main: Starting Locust 2.20.1
[2024-01-11 15:14:18,514] ornn/INFO/locust.runners: Ramping to 1 users at a rate of 1.00 per second
[2024-01-11 15:14:18,515] ornn/INFO/locust.runners: All users spawned: {"DemoTestUser": 1} (1 total users)
creating embedder...
[2024-01-11 15:14:20,530] ornn/INFO/sentence_transformers.SentenceTransformer: Load pretrained
[2024-01-11 15:14:22,433] ornn/INFO/sentence_transformers.SentenceTransformer: Use pytorch device: cuda
initializing milvus client...
Exception in thread Thread-3 (_run):
Traceback (most recent call last):
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "src/python/grpcio/grpc/_cython/_cygrpc/thread.pyx.pxi", line 53, in grpc._cython.cygrpc._run_with_context._run
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/grpc/_channel.py", line 1843, in _poll_connectivity
    event = channel.watch_connectivity_state(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 538, in grpc._cython.cygrpc.Channel.watch_connectivity_state
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 416, in grpc._cython.cygrpc._watch_connectivity_state
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/threading.py", line 264, in __enter__
    def __enter__(self):

KeyboardInterrupt
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/locust/user/users.py", line 187, in run_user
    user.run()
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/locust/user/users.py", line 149, in run
    self.on_start()
  File "/home/zeio/villm/test/load/demo.py", line 20, in on_start
    self.client = Milvus(
                  ^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/langchain_community/vectorstores/milvus.py", line 155, in __init__
    self.alias = self._create_connection_alias(connection_args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/langchain_community/vectorstores/milvus.py", line 221, in _create_connection_alias
    connections.connect(alias=alias, **connection_args)
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/pymilvus/orm/connections.py", line 356, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/pymilvus/orm/connections.py", line 302, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 134, in _wait_for_channel_ready
    self._setup_identifier_interceptor(self._user, timeout=timeout)
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 251, in _setup_identifier_interceptor
    self._identifier = self.__internal_register(user, host, timeout=timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/pymilvus/decorators.py", line 125, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/pymilvus/decorators.py", line 164, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/pymilvus/decorators.py", line 194, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 1768, in __internal_register
    response = self._stub.Connect(request=req)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/grpc/_interceptor.py", line 277, in __call__
    response, ignored_call = self._with_call(
                             ^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/grpc/_interceptor.py", line 329, in _with_call
    call = self._interceptor.intercept_unary_unary(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/pymilvus/client/interceptor.py", line 35, in intercept_unary_unary
    response = continuation(new_details, next(new_request_iterator))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/grpc/_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/grpc/_channel.py", line 1175, in with_call
    ) = self._blocking(
        ^^^^^^^^^^^^^^^
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/site-packages/grpc/_channel.py", line 1142, in _blocking
    event = call.next_event()
            ^^^^^^^^^^^^^^^^^
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 366, in grpc._cython.cygrpc.SegregatedCall.next_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 189, in grpc._cython.cygrpc._next_call_event
  File "/home/zeio/miniconda3/envs/villm/lib/python3.11/threading.py", line 264, in __enter__
    def __enter__(self):

KeyboardInterrupt
2024-01-11T12:19:49Z <Greenlet at 0x7f331e46b7e0: run_user(<demo.DemoTestUser object at 0x7f331e496850>)> failed with KeyboardInterrupt

[2024-01-11 15:19:49,527] ornn/INFO/locust.main: Shutting down (exit code 0)
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                         0     0(0.00%) |      0       0       0      0 |    0.00        0.00

Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------

^C^C^C
```

### Command line

locust -f test/load/demo.py

### Locustfile contents

```python3
The contents of `test/load/demo.py`:


from time import sleep

from locust import HttpUser, task
from langchain.vectorstores.milvus import Milvus
from villm.index.ChromaCollector import HuggingFaceEmbedder

from test.load.example import HOST, PORT
from test.load.quick import EMBEDDING_MODEL, COLLECTION


class DemoTestUser(HttpUser):
    host = HOST
    port = PORT

    def on_start(self):
        print('creating embedder...')
        embedder = HuggingFaceEmbedder(model_name = EMBEDDING_MODEL)

        print('initializing milvus client...')
        self.client = Milvus(
            embedder.get_embedder(),
            connection_args = {'host': HOST, 'port': PORT},
            collection_name = COLLECTION
        )

        print('ready to make queries')

    @task
    def query(self):
        print('starting task...')

        sleep(2)

        print('ending task...')
```

### Python version

Python 3.11.5

### Locust version

2.20.1

### Operating system

6.1.57-gentoo-x86_64

**Comment by zeionara** [comment]
Using `GprcUser` instead of `HttpUser` as written [here](https://docs.locust.io/en/stable/testing-other-systems.html#grpc) helped to avoid deadlock. The resulting `test/load/demo.py`:

```py
from time import sleep

from locust import task
from langchain.vectorstores.milvus import Milvus
from pymilvus.grpc_gen.milvus_pb2_grpc import MilvusServiceStub

from villm.index.ChromaCollector import HuggingFaceEmbedder

from test.load.example import HOST, PORT
from test.load.quick import EMBEDDING_MODEL, COLLECTION
from test.load.GrpcUser import GrpcUser


class DemoTestUser(GrpcUser):
    host = HOST
    port = PORT

    stub_class = MilvusServiceStub

    def on_start(self):
        print('creating embedder...')
        embedder = HuggingFaceEmbedder(model_name = EMBEDDING_MODEL)

        print('initializing milvus client...')
        self.client = Milvus(
            embedder.get_embedder(),
            connection_args = {'host': HOST, 'port': PORT},
            collection_name = COLLECTION
        )

        print('ready to make queries')

    @task
    def query(self):
        print('starting task...')

        sleep(2)

        print('ending task...')
```

The contents of `test/load/GrpcUser.py`:

```py
import time
from typing import Any, Callable
import grpc
import grpc.experimental.gevent as grpc_gevent
from grpc_interceptor import ClientInterceptor
from locust import User
from locust.exception import LocustError

# patch grpc so that it uses gevent instead of asyncio
grpc_gevent.init_gevent()


class LocustInterceptor(ClientInterceptor):
    def __init__(self, environment, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.env = environment

    def intercept(
        self,
        method: Callable,
        request_or_iterator: Any,
        call_details: grpc.ClientCallDetails,
    ):
        response = None
        exception = None
        start_perf_counter = time.perf_counter()
        response_length = 0
        try:
            response = method(request_or_iterator, call_details)
            response_length = response.result().ByteSize()
        except grpc.RpcError as e:
            exception = e

        self.env.events.request.fire(
            request_type="grpc",
            name=call_details.method,
            response_time=(time.perf_counter() - start_perf_counter) * 1000,
            response_length=response_length,
            response=response,
            context=None,
            exception=exception,
        )
        return response


class GrpcUser(User):
    abstract = True
    stub_class = None

    def __init__(self, environment):
        super().__init__(environment)
        for attr_value, attr_name in ((self.host, "host"), (self.stub_class, "stub_class")):
            if attr_value is None:
                raise LocustError(f"You must specify the {attr_name}.")

        self._channel = grpc.insecure_channel(self.host)
        interceptor = LocustInterceptor(environment=environment)
        self._channel = grpc.intercept_channel(self._channel, interceptor)

        self.stub = self.stub_class(self._channel)
```
