### ISSUE TITLE
User Classes with Empty Tasks Results in TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by hangonlyra** [locustio/locust#2694]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

After upgrading from 2.19.0 to 2.25.0 (this bug exists in 2.21.0+), I get 
```
Traceback (most recent call last):
  File "/Users/hang/Source/qa_automation/performance/playwright/env/bin/locust", line 8, in <module>
    sys.exit(main())
  File "/Users/hang/Source/qa_automation/performance/playwright/env/lib/python3.8/site-packages/locust/main.py", line 493, in main
    web_ui = environment.create_web_ui(
  File "/Users/hang/Source/qa_automation/performance/playwright/env/lib/python3.8/site-packages/locust/env.py", line 186, in create_web_ui
    self.web_ui = WebUI(
  File "/Users/hang/Source/qa_automation/performance/playwright/env/lib/python3.8/site-packages/locust/web.py", line 142, in __init__
    self.update_template_args()
  File "/Users/hang/Source/qa_automation/performance/playwright/env/lib/python3.8/site-packages/locust/web.py", line 630, in update_template_args
    {
  File "/Users/hang/Source/qa_automation/performance/playwright/env/lib/python3.8/site-packages/locust/web.py", line 631, in <dictcomp>
    user_class_name: [task.__name__ for task in user_class]
TypeError: 'NoneType' object is not iterable
```
This was trace back to an `User` class that has no `tasks` defined. The reason that class exists in my project is because all my other user classes inherit from it.

The fix is actually very simple too:

In `locust/main.py`, on line 129 change
```python3
available_user_tasks[key] = value.tasks or None
```
to
```python3
available_user_tasks[key] = value.tasks or []
```
since everywhere else `available_user_tasks` is expected to be iterable.

For now one can just work around it by adding:
```python3
@task
def bogus(self):
# Work around for this bug: https://github.com/locustio/locust/issues/2694
    pass
```

to the class affected by this.

### Command line

locust

### Locustfile contents

```python3
from locust import User

class CustomUser(User):
    pass
```

### Python version

3.8, 3.9, 3.10

### Locust version

2.21.0 to 2.25.0

### Operating system

Linux or Mac OS

**Comment by cyberw** [comment]
Good find. Do you think you can make a PR for it? I’d do it myself but I’m typing this on a very small keyboard :)

**Comment by cyberw** [comment]
Having user classes with no tasks is an error (but shouldnt give this weird crash).

If you dont want instances of a class to be created, just set the abstract = True attribute on the class.

Your fix might still be appropriate..

**Comment by hangonlyra** [comment]
Oh that's fair. Thanks for the analysis and suggestion. I'll prep a PR. I think it will still be nice to have it not crash like that. Plus the change is minute.
