### ISSUE TITLE
tag doesn't work fine

### ISSUE THREAD

**Issue by evanchaoli** [locustio/locust#2849]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

With this simple locusfile:

```
from locust import HttpUser, task, tag


class RevisionApiUser(HttpUser):
    @tag('revision')
    @task
    def get_commit_list(self):
        print("revision")


class CBotApiUser(HttpUser):
    @tag('cbot')
    @task
    def get_commits(self):
        print("cbot")
```

Then run locust with a tag specified:

```
$ locust --tags cbot
[2024-08-14 15:05:43,870] C02GM2X6MD6R/ERROR/locust.user.task: No tasks defined on RevisionApiUser. Use the @task decorator or set the 'tasks' attribute of the User (or mark it as abstract = True if you only intend to subclass it)
Traceback (most recent call last):
  File "/Users/chaol/venv/3.9/lib/python3.9/site-packages/locust/user/task.py", line 335, in run
    self.schedule_task(self.get_next_task())
  File "/Users/chaol/venv/3.9/lib/python3.9/site-packages/locust/user/task.py", line 479, in get_next_task
    raise Exception(
Exception: No tasks defined on RevisionApiUser. Use the @task decorator or set the 'tasks' attribute of the User (or mark it as abstract = True if you only intend to subclass it)
```

From the UI, the test looks run properly, only `CBotApiUser` is executed.  However, the terminal keeps scrolling the error message.

### Command line

locust --tags cbot

### Locustfile contents

```python3
from locust import HttpUser, task, tag


class RevisionApiUser(HttpUser):
    @tag('revision')
    @task
    def get_commit_list(self):
        print("revision")


class CBotApiUser(HttpUser):
    @tag('cbot')
    @task
    def get_commits(self):
        print("cbot")
```

### Python version

3.9.19

### Locust version

locust 2.31.2 from /Users/chaol/venv/3.9/lib/python3.9/site-packages/locust (Python 3.9.19, OpenSSL 3.3.0)

### Operating system

MacOS

**Comment by cyberw** [comment]
This is kind of intentional. You are spawning a user with no tasks (after filtering tags) which is usually a mistake, so we should log an error message (although I guess it would be enough to do it once, PRs fixing that would be welcome.)

Instead, you can filter by User class, e.g. `locust CBotApiUser`, or use `--config-users` to temporarily give the user class `weight = 0`.

**Comment by vijay59122** [comment]
@cyberw , please assign it to me. I would like to work on this.

**Comment by skirtan1** [comment]
I think this is fixed already. I can see the warning message once

See:
![Screenshot from 2024-10-18 23-42-21](https://github.com/user-attachments/assets/4acd786e-55a0-4d53-b291-49bf9133d7e3)

**Comment by cyberw** [comment]
The problem I was referring to is that it gets logged once per user instance. When I think about it though, idk if it is worth fixing though.

**Comment by vijay59122** [comment]
@skirtan1 , looks like you ran with only one user and that user picked CBotApiUser(alphabetically ordered). If you run with more than one user then you can see the issue.

@cyberw , it would be still good if it gets logged once per user instance instead of throwing exceptions right?

**Comment by cyberw** [comment]
Yes!

**Comment by vijay59122** [comment]
https://github.com/locustio/locust/pull/2957

**Comment by cyberw** [comment]
@vijay59122 That PR does more than I expected. I dont want to change any behaviour apart from the log spam.
