### ISSUE TITLE
Unable to install locusio

### ISSUE THREAD

**Issue by sivabudh** [locustio/locust#336]
Hello,

I tried to install locustio via pip as follows:

`pip install locustio`

Then I ran into the following issue:

    copying gevent/wsgi.py -> build/lib.macosx-10.10-x86_64-3.4/gevent

    running build_ext

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/private/var/folders/2k/hb_2nnks2g36msntyvbmqpwr0000gn/T/pip-build-eb4393nv/gevent/setup.py", line 317, in <module>

        run_setup(ext_modules)

      File "/private/var/folders/2k/hb_2nnks2g36msntyvbmqpwr0000gn/T/pip-build-eb4393nv/gevent/setup.py", line 312, in run_setup

        "Development Status :: 4 - Beta"])

      File "/Users/Pac/.pyenv/versions/3.4.3/lib/python3.4/distutils/core.py", line 148, in setup

        dist.run_commands()

      File "/Users/Pac/.pyenv/versions/3.4.3/lib/python3.4/distutils/dist.py", line 955, in run_commands

        self.run_command(cmd)

      File "/Users/Pac/.pyenv/versions/3.4.3/lib/python3.4/distutils/dist.py", line 974, in run_command

        cmd_obj.run()

      File "/Users/Pac/.pyenv/versions/3.4.3/lib/python3.4/site-packages/setuptools/command/install.py", line 61, in run

        return orig.install.run(self)

      File "/Users/Pac/.pyenv/versions/3.4.3/lib/python3.4/distutils/command/install.py", line 539, in run

        self.run_command('build')

      File "/Users/Pac/.pyenv/versions/3.4.3/lib/python3.4/distutils/cmd.py", line 313, in run_command

        self.distribution.run_command(command)

      File "/Users/Pac/.pyenv/versions/3.4.3/lib/python3.4/distutils/dist.py", line 974, in run_command

        cmd_obj.run()

      File "/Users/Pac/.pyenv/versions/3.4.3/lib/python3.4/distutils/command/build.py", line 126, in run

        self.run_command(cmd_name)

      File "/Users/Pac/.pyenv/versions/3.4.3/lib/python3.4/distutils/cmd.py", line 313, in run_command

        self.distribution.run_command(command)

      File "/Users/Pac/.pyenv/versions/3.4.3/lib/python3.4/distutils/dist.py", line 974, in run_command

        cmd_obj.run()

      File "/Users/Pac/.pyenv/versions/3.4.3/lib/python3.4/distutils/command/build_ext.py", line 339, in run

        self.build_extensions()

      File "/Users/Pac/.pyenv/versions/3.4.3/lib/python3.4/distutils/command/build_ext.py", line 448, in build_extensions

        self.build_extension(ext)

      File "/private/var/folders/2k/hb_2nnks2g36msntyvbmqpwr0000gn/T/pip-build-eb4393nv/gevent/setup.py", line 234, in build_extension

        self.gevent_prepare(ext)

      File "/private/var/folders/2k/hb_2nnks2g36msntyvbmqpwr0000gn/T/pip-build-eb4393nv/gevent/setup.py", line 231, in gevent_prepare

        configure(self, ext)

      File "/private/var/folders/2k/hb_2nnks2g36msntyvbmqpwr0000gn/T/pip-build-eb4393nv/gevent/setup.py", line 139, in configure_libev

        make_universal_header('config.h', 'SIZEOF_LONG', 'SIZEOF_SIZE_T', 'SIZEOF_TIME_T')

      File "/private/var/folders/2k/hb_2nnks2g36msntyvbmqpwr0000gn/T/pip-build-eb4393nv/gevent/setup.py", line 111, in make_universal_header

        print >>f, line

    TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'

    Running '/bin/sh /private/var/folders/2k/hb_2nnks2g36msntyvbmqpwr0000gn/T/pip-build-eb4393nv/gevent/libev/configure > configure-output.txt' in /private/var/folders/2k/hb_2nnks2g36msntyvbmqpwr0000gn/T/pip-build-eb4393nv/gevent/build/temp.macosx-10.10-x86_64-3.4/libev

    ----------------------------------------
    Command "/Users/Pac/.pyenv/versions/3.4.3/bin/python3.4 -c "import setuptools, tokenize;__file__='/private/var/folders/2k/hb_2nnks2g36msntyvbmqpwr0000gn/T/pip-build-eb4393nv/gevent/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/2k/hb_2nnks2g36msntyvbmqpwr0000gn/T/pip-lnmc3qyc-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/2k/hb_2nnks2g36msntyvbmqpwr0000gn/T/pip-build-eb4393nv/gevent

What could be the reason? I'm running python 3.4.3.

Thanks.

**Comment by sivabudh** [comment]
My operating system is Mac OS X 10.10.5.

**Comment by cgoldberg** [comment]
@sivabudh 
Locust is not currently compatible with Python 3.x.
try again with Python 2.7.

**Comment by nryoung** [comment]
be aware there is an open issue to add support for Python3 #279

**Comment by sivabudh** [comment]
Thanks both @cgoldberg and @nryoung. Sorry I didn't read your doc carefully!
