### ISSUE TITLE
Locust 0.7.3: TypeError trying to run test

### ISSUE THREAD

**Issue by smalenfant** [locustio/locust#338]
I don't think I had this problem previously and not sure how to fix this. Any pointers?
I'm using the example from the quick start.

```
(csx)[me@ni-fl-01 csx]$ locust -f example.py -H http://tata
[2015-09-16 08:29:35,679] ni-fl-01.ni.coxlab.net/INFO/locust.main: Starting web monitor at *:8089
[2015-09-16 08:29:35,680] ni-fl-01.ni.coxlab.net/ERROR/stderr: Traceback (most recent call last):
[2015-09-16 08:29:35,680] ni-fl-01.ni.coxlab.net/ERROR/stderr: File "/home/smalenfa/csx/bin/locust", line 8, in <module>
[2015-09-16 08:29:35,680] ni-fl-01.ni.coxlab.net/ERROR/stderr: 
[2015-09-16 08:29:35,680] ni-fl-01.ni.coxlab.net/ERROR/stderr: load_entry_point('locustio==0.7.3', 'console_scripts', 'locust')()
[2015-09-16 08:29:35,680] ni-fl-01.ni.coxlab.net/ERROR/stderr: File "/home/smalenfa/csx/lib/python2.6/site-packages/locust/main.py", line 437, in main
[2015-09-16 08:29:35,680] ni-fl-01.ni.coxlab.net/ERROR/stderr: 
[2015-09-16 08:29:35,680] ni-fl-01.ni.coxlab.net/ERROR/stderr: gevent.signal(signal.SIGTERM, sig_term_handler)
[2015-09-16 08:29:35,680] ni-fl-01.ni.coxlab.net/ERROR/stderr: TypeError
[2015-09-16 08:29:35,680] ni-fl-01.ni.coxlab.net/ERROR/stderr: :
[2015-09-16 08:29:35,680] ni-fl-01.ni.coxlab.net/ERROR/stderr: 'module' object is not callable
[2015-09-16 08:29:35,680] ni-fl-01.ni.coxlab.net/ERROR/stderr: 
```

**Comment by smalenfant** [comment]
I installed on another machine that never had gevent/locustio and everything is working fine. I'll just close this.

**Comment by MarcSteven** [comment]
It's still existing

**Comment by heyman** [comment]
> It's still existing

Please provide more details. Do you get the same stacktrace? What Locust version ate you using? Etc. Thanks!

**Comment by SteveYf** [comment]
I also encountered the same problem, locust version is 0.11.0, gevent version is 20.4.0, I am running on windows, could this be a problem with the version?

**Comment by SteveYf** [comment]
I am using python3.7, I updated the version of gevent package to 1.4.0, no problem

**Comment by heyman** [comment]
@SteveYf Hmm, we currently specify the gevent version to >= 1.5 (since 1.4 has a problem with Python 3.8 IIRC).
