### ISSUE TITLE
does not work in python 3.4 virtualenv

### ISSUE THREAD

**Issue by xrmx** [locustio/locust#359]
It installs fine but fails to import needed modules.

```
$ python3.4 --version
Python 3.4.3+
$ virtualenv --python python3.4 foo
$ ./foo/bin/pip install locustio
$ . foo/bin/activate
(foo)$ locust
Traceback (most recent call last):
  File "/home/rm/work/foo/bin/locust", line 9, in <module>
    load_entry_point('locustio==0.7.3', 'console_scripts', 'locust')()
  File "/home/rm/work/foo/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/rm/work/foo/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/home/rm/work/foo/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/home/rm/work/foo/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/rm/work/foo/lib/python3.4/site-packages/locust/__init__.py", line 1, in <module>
    from core import HttpLocust, Locust, TaskSet, task
ImportError: No module named 'core'
```

**Comment by xrmx** [comment]
Just found out #279, sorry for the noise :)
