### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by alexandrul** [locustio/locust#431]
Hi,

```test_client_basic_auth``` is considered passed even if it raises an exception:
* on my PC (Python 3.5.1 x64 under Win 7 x64)
* on Travis (you can look at the actual output: https://travis-ci.org/locustio/locust/jobs/136133249)

```
[2016-06-08 12:29:56,811] ERROR in app: Exception on /basic_auth [GET]
Traceback (most recent call last):
  File "/home/travis/build/locustio/locust/.tox/py35/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/travis/build/locustio/locust/.tox/py35/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/travis/build/locustio/locust/.tox/py35/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/travis/build/locustio/locust/.tox/py35/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/travis/build/locustio/locust/.tox/py35/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/travis/build/locustio/locust/.tox/py35/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/travis/build/locustio/locust/locust/test/testcases.py", line 84, in basic_auth
    auth = base64.b64decode(request.headers.get("Authorization").replace("Basic ", "")).decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by alexandrul** [comment]
This change works for me:

```auth = base64.b64decode(request.headers.get("Authorization", '').replace("Basic ", "")).decode('utf-8')```

**Comment by heyman** [comment]
Thanks!

**Comment by alexandrul** [comment]
Thank you :+1:
