### ISSUE TITLE
Contradiction on supported versions

### ISSUE THREAD

**Issue by Bonifacio2** [locustio/locust#461]
[README.md](https://github.com/locustio/locust/blob/master/README.md) says that it supports Python 3.4 while [installation.rst](https://github.com/locustio/locust/blob/master/docs/installation.rst), the installation documentation, says Python 3 is not currently supported.

Which one is correct?

**Comment by codeadict** [comment]
I will test on 3.4, tested on 3.5 and i'm getting an import error:

```
File "/home/codeadict/.virtualenvs/cloud-api/bin/locust", line 7, in <module>
    from locust.main import main
  File "/home/codeadict/.virtualenvs/cloud-api/local/lib/python3.5/site-packages/locust/__init__.py", line 1, in <module>
    from core import HttpLocust, Locust, TaskSet, task
ImportError: cannot import name 'HttpLocust'
```

Will make a fix for it soon

**Comment by heyman** [comment]
The latest master should support Python 3, but the latest PyPI release does currently not.

**Comment by myrinx** [comment]
Python 3.5.2 via pip3 install does not work unfortunately. Same issue as above.

**Comment by cgoldberg** [comment]
@myrinx 
please see the comment posted *directly* before yours.  If you install from master, it is compatible with Python 3.

**Comment by myrinx** [comment]
I have done that. I downloaded the git repo (on windows so not git clone) and ran setup.py build install.

This installs everything for python 3, but when running a sample script, I get the message:

Traceback (most recent call last):
  File "locust.py", line 1, in <module>
    from locust import HttpLocust, TaskSet
  File "locust.py", line 1, in <module>
    from locust import HttpLocust, TaskSet
ImportError: cannot import name 'HttpLocust'

**Comment by myrinx** [comment]
I've spotted the flaw. when naming the locustfile to use locust.py, it doesn't work...

**Comment by heyman** [comment]
@myrinx Ah, yes. We should maybe check for that explicitly and warn+fail, since it has come up a couple of times. 

Glad you found it!

**Comment by cgoldberg** [comment]
see #546

**Comment by nags28** [comment]
### even I am facing the same issue 

**my python version**
 python3 --version
Python 3.6.9
pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

###  if I check the locust version I am facing the below error
**locust -v** 

Traceback (most recent call last):
  File "/usr/local/bin/locust", line 11, in <module>
    load_entry_point('locust', 'console_scripts', 'locust')()
  File "/locust-task/src/locust/locust/main.py", line 123, in main
    docstring, user_classes, shape_class = load_locustfile(locustfile)
  File "/locust-task/src/locust/locust/main.py", line 79, in load_locustfile
    imported = source.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/locust-task/locustfile.py", line 1, in <module>
    from locust import HttpLocust, TaskSet, task, InterruptTaskSet
ImportError: cannot import name 'InterruptTaskSet'

can someone help me to resolve it
