### ISSUE TITLE
pydoc.locate breaks after importing locust

### ISSUE THREAD

**Issue by carn1x** [locustio/locust#499]
I was hoping to use `pydoc.locate()` to import tasks by string, so that I can specify tasks by string in a settings file.

However it seems that importing `locust` upsets this process. Take for instance the following basic module/class:

`tasks.py`:
```
class Klass:
    def meth(self):
        pass
```

Then in a python shell:
```
>>> from pydoc import locate
>>> locate('tasks.Klass.meth')
<unbound method Klass.meth>
```

However if I involve locust, then `locate()` breaks, though the module is still fine.
```
>>> from pydoc import locate
>>> import locust
>>> locate('tasks.Klass.meth')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/pydoc.py", line 1504, in locate
    nextmodule = safeimport(join(parts[:n+1], '.'), forceload)
  File "/usr/lib/python2.7/pydoc.py", line 341, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in tasks.Klass - <type 'exceptions.ImportError'>: No module named Klass
>>> from tasks import Klass
>>> Klass.meth
<unbound method Klass.meth>
```

Whaat?

**Comment by justiniso** [comment]
Please let us know if you're able to track down the issue!
