### ISSUE TITLE
No module named 'core' error

### ISSUE THREAD

**Issue by CakeEddy** [locustio/locust#531]
I saw that there was an issue with this earlier but it was closed (back in Oct 2016). But I'm seeing the exact same thing.
I'm running Mint (ubuntu) and I'm seeing the "No module named 'core'" issue.
...
eddy-ca-nb-linux03 - ~/GIT/locustProject
eddy - 01:57:35 $ locust
Traceback (most recent call last):
  File "/usr/local/bin/locust", line 9, in <module>
    load_entry_point('locustio==0.7.5', 'console_scripts', 'locust')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/locust/__init__.py", line 1, in <module>
    from core import HttpLocust, Locust, TaskSet, task
ImportError: No module named 'core'

 eddy-ca-nb-linux03 - ~/GIT/locustProject
eddy - 01:59:22 $ python -V
Python 2.7.12

eddy-ca-nb-linux03 - ~/GIT/locustProject
eddy - 02:10:58 $ python3 -V
Python 3.5.2
...

I installed locust via pip install which installs locust into the /usr/local/lib/python3.5/dist-packages/locust/ directory.

Any help would be greatly appreciated.

**Comment by CakeEddy** [comment]
Seems that installing locust with this command fixed the issue for me... 

sudo pip install -e git://github.com/locustio/locust.git@master#egg=locustio
