### ISSUE TITLE
ImportError: No module named 'core - Python 3.5.0, 3.5.2

### ISSUE THREAD

**Issue by shashidesai** [locustio/locust#572]
Github Documentation says --> Locust supports Python 2.7, 3.3, 3.4, 3.5, and 3.6.
I tried running with python 3.5.0 and 3.5.2 and saw the below error. But I didn't see the error with python 2.7.12 

`$ locust -H http://localhost:8000
Traceback (most recent call last):
  File "/Users/shashi.desai/.pyenv/versions/locust/bin/locust", line 9, in <module>
    load_entry_point('locustio==0.7.5', 'console_scripts', 'locust')()
  File "/Users/shashi.desai/.pyenv/versions/3.5.0/envs/locust/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/shashi.desai/.pyenv/versions/3.5.0/envs/locust/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/Users/shashi.desai/.pyenv/versions/3.5.0/envs/locust/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/Users/shashi.desai/.pyenv/versions/3.5.0/envs/locust/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/shashi.desai/.pyenv/versions/3.5.0/envs/locust/lib/python3.5/site-packages/locust/__init__.py", line 1, in <module>
    from core import HttpLocust, Locust, TaskSet, task
ImportError: No module named 'core'`

**Comment by shashidesai** [comment]
my bad, I just saw your tweet which said to use specific version which supports python 3+ 
"Locust 0.8a1 has been released! Python 3 support! Please try it out, and report bugs. Install using:" `pip install locustio==0.8a1`
https://twitter.com/locustio/status/801736746727784448
