### ISSUE TITLE
Install breaks on Win7 Py3.3 Locust 0.8.1

### ISSUE THREAD

**Issue by DevonStrawn** [locustio/locust#668]
### Description of issue / feature request

Install fails

### Actual behavior

Exception during install:

```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 3997: character maps to <undefined>
```

### Environment settings (for bug reports)

- OS: Windows 7
- Python version: 3.3.0
- Locust version: 0.8.1
- Git for Windows: 2.9.2

### Steps to reproduce (for bug reports)

```
$ pip install locustio
```

### Pip stack trace:

```
$ pip install locustio
Downloading/unpacking locustio
  Downloading locustio-0.8.1.tar.gz (222kB): 222kB downloaded
  Running setup.py egg_info for package locustio

Downloading/unpacking gevent>=1.2.2 (from locustio)
  Downloading gevent-1.2.2.tar.gz (3.1MB): 3.1MB downloaded
  Running setup.py egg_info for package gevent
    C:\Python33\Lib\distutils\dist.py:257: UserWarning: Unknown distribution option: 'cffi_modules'
      warnings.warn(msg)

    warning: no files found matching 'changelog.rst'
    warning: no files found matching 'known_failures.py'
    warning: no files found matching '.pep8'
    no previously-included directories found matching '*\__pycache__'
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching '*.lo' found anywhere in distribution
    warning: no previously-included files matching '*.la' found anywhere in distribution
    warning: no previously-included files matching 'config.log' found anywhere in distribution
    warning: no previously-included files matching 'config.status' found anywhere in distribution
    no previously-included directories found matching 'doc\_build'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.coverage' found under directory 'src\greentest'
    no previously-included directories found matching 'src\greentest\htmlcov'
    warning: no previously-included files matching 'stamp-h?' found under directory 'deps\c-ares'
    warning: no previously-included files matching 'ares_build.h.orig' found under directory 'deps\c-ares'
    no previously-included directories found matching 'deps\libev\.deps'
    warning: no previously-included files matching 'Makefile' found under directory 'deps\libev'
    warning: no previously-included files matching 'libtool' found under directory 'deps\libev'
    warning: no previously-included files matching 'stamp-h?' found under directory 'deps\libev'
    warning: no previously-included files matching 'config.h' found under directory 'deps\libev'
    warning: no previously-included files matching '_corecffi.c' found under directory 'src\gevent'
    warning: no previously-included files found matching 'Makefile'
    warning: no previously-included files found matching 'configure-output'
Downloading/unpacking flask>=0.10.1 (from locustio)
  Downloading Flask-0.12.2.tar.gz (548kB): 548kB downloaded
  Running setup.py egg_info for package flask

    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    no previously-included directories found matching 'docs\_build'
    no previously-included directories found matching 'docs\_themes'
Downloading/unpacking requests>=2.9.1 (from locustio)
  Downloading requests-2.18.4.tar.gz (126kB): 126kB downloaded
  Running setup.py egg_info for package requests

    warning: no files found matching 'NOTICE'
Exception:
Traceback (most recent call last):
  File "c:\Python33\lib\site-packages\pip\basecommand.py", line 139, in main
    status = self.run(options, args)
  File "c:\Python33\lib\site-packages\pip\commands\install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "c:\Python33\lib\site-packages\pip\req.py", line 1062, in prepare_files
    req_to_install.assert_source_matches_version()
  File "c:\Python33\lib\site-packages\pip\req.py", line 371, in assert_source_matches_version
    version = self.installed_version
  File "c:\Python33\lib\site-packages\pip\req.py", line 367, in installed_version
    return self.pkg_info()['version']
  File "c:\Python33\lib\site-packages\pip\req.py", line 334, in pkg_info
    data = self.egg_info_data('PKG-INFO')
  File "c:\Python33\lib\site-packages\pip\req.py", line 274, in egg_info_data
    data = fp.read()
  File "C:/Python33/Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 3997: character maps to <undefined>
```

**Comment by DevonStrawn** [comment]
Update: upgraded Python to 3.4, and the install works.

The install bug might be specific to Python 3.3.

**Comment by cgoldberg** [comment]
the stacktrace shows it happens when installing the requests package
