### ISSUE TITLE
how to run the master branch

### ISSUE THREAD

**Issue by jjnha** [locustio/locust#732]
hi, i have pulled the master branch code

when i  execute the command   python main.py .  something wrong happened

C:\Python27\python.exe D:/python-project/locust/locust/main.py
Traceback (most recent call last):
  File "D:/python-project/locust/locust/main.py", line 14, in <module>
    from . import events, runners, web
  File "C:\Python27\lib\site-packages\gevent\builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ValueError: Attempted relative import in non-package

how to deal with it ?

**Comment by jjnha** [comment]
"D:\Program Files\python3\python.exe" D:/python-project/locust-master/locust/main.py
Traceback (most recent call last):
  File "D:/python-project/locust-master/locust/main.py", line 14, in <module>
    from . import events, runners, web
ImportError: cannot import name 'events'

**Comment by jjnha** [comment]
the python -V is  2.7.13

D:\python-project\locust-master\locust>python main.py
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from . import events, runners, web
  File "C:\Python27\lib\site-packages\gevent\builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ValueError: Attempted relative import in non-package

**Comment by heyman** [comment]
Try to run:

```
python setup.py install
```

And if Locust installs successfully you should hopefully be able to run locust:

```
locust --help
```

**Comment by jjnha** [comment]
@heyman   i know  how to use the locust.  i have run  " python setup.py install" 
but  i  want to  debug the source code.  is the main function   the entrance to the project?
when i execute the  command  python main.py , the error comes

the python -V is 2.7.13

D:\python-project\locust-master\locust>python main.py
Traceback (most recent call last):
File "main.py", line 14, in 
from . import events, runners, web
File "C:\Python27\lib\site-packages\gevent\builtins.py", line 93, in import
result = _import(*args, **kwargs)
ValueError: Attempted relative import in non-package

what should i do ?

thanks

**Comment by cgoldberg** [comment]
see: https://github.com/locustio/locust/issues/613
