### ISSUE TITLE
master slave locust problem show only 2 users ?

### ISSUE THREAD

**Issue by MarwaAbed** [locustio/locust#836]
hi  all,
I'm using mqtt-locust from this site(https://github.com/ajm188/mqtt-locust) it works when I run it normally put when I try to use it in distribution mode it output only two users per slave and no error has been shown in master just in slave the followin error show the following error  
```
/INFO/locust.main: Starting Locust 0.8
[2018-07-06 16:41:21,347] ip-172-31-94-187/INFO/locust.runners: Hatching and swarming 40000 clients at the rate 3000 clients/s...
[2018-07-06 16:41:21,350] ip-172-31-94-187/ERROR/stderr: Traceback (most recent call last):
[2018-07-06 16:41:21,350] ip-172-31-94-187/ERROR/stderr: File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/threadpool.py", line 281, in _worker
[2018-07-06 16:41:21,350] ip-172-31-94-187/ERROR/stderr: value = func(*args, **kwargs)
[2018-07-06 16:41:21,350] ip-172-31-94-187/ERROR/stderr: error: getaddrinfo() argument 2 must be integer or string
[2018-07-06 16:41:21,351] ip-172-31-94-187/ERROR/stderr: 2018-07-06T16:41:21Z
[2018-07-06 16:41:21,351] ip-172-31-94-187/ERROR/stderr:
[2018-07-06 16:41:21,351] ip-172-31-94-187/ERROR/stderr: (<ThreadPool at 0x7fd151238e10 1/1/10 hub=<Hub at 0x7fd15499bb50 thread_ident=0x140537104705280>>, <built-in function getaddrinfo>) failed with error
[2018-07-06 16:41:21,352] ip-172-31-94-187/ERROR/stderr: Traceback (most recent call last):
[2018-07-06 16:41:21,352] ip-172-31-94-187/ERROR/stderr: File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
[2018-07-06 16:41:21,353] ip-172-31-94-187/ERROR/stderr: File "/home/ubuntu/.local/lib/python2.7/site-packages/locust/runners.py", line 114, in start_locust
[2018-07-06 16:41:21,353] ip-172-31-94-187/ERROR/stderr: locust().run()
[2018-07-06 16:41:21,353] ip-172-31-94-187/ERROR/stderr: File "/home/ubuntu/working_locust/mqtt_locust.py", line 139, in __init__
[2018-07-06 16:41:21,353] ip-172-31-94-187/ERROR/stderr: self.client.connect(host, port=port)
[2018-07-06 16:41:21,353] ip-172-31-94-187/ERROR/stderr: File "/home/ubuntu/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 612, in connect
[2018-07-06 16:41:21,354] ip-172-31-94-187/ERROR/stderr: return self.reconnect()
[2018-07-06 16:41:21,354] ip-172-31-94-187/ERROR/stderr: File "/home/ubuntu/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 734, in reconnect
[2018-07-06 16:41:21,354] ip-172-31-94-187/ERROR/stderr: sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
[2018-07-06 16:41:21,354] ip-172-31-94-187/ERROR/stderr: File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/socket.py", line 83, in create_connection
[2018-07-06 16:41:21,354] ip-172-31-94-187/ERROR/stderr: addrs = list(getaddrinfo(host, port, 0, SOCK_STREAM))
[2018-07-06 16:41:21,355] ip-172-31-94-187/ERROR/stderr: File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/_socketcommon.py", line 199, in getaddrinfo
[2018-07-06 16:41:21,355] ip-172-31-94-187/ERROR/stderr: return get_hub().resolver.getaddrinfo(host, port, family, socktype, proto, flags)
[2018-07-06 16:41:21,355] ip-172-31-94-187/ERROR/stderr: File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/resolver/thread.py", line 65, in getaddrinfo
[2018-07-06 16:41:21,355] ip-172-31-94-187/ERROR/stderr: return self.pool.apply(_socket.getaddrinfo, args, kwargs)
[2018-07-06 16:41:21,355] ip-172-31-94-187/ERROR/stderr: File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/pool.py", line 159, in apply
[2018-07-06 16:41:21,355] ip-172-31-94-187/ERROR/stderr: return self.spawn(func, *args, **kwds).get()
[2018-07-06 16:41:21,356] ip-172-31-94-187/ERROR/stderr: File "src/gevent/event.py", line 381, in gevent._event.AsyncResult.get
[2018-07-06 16:41:21,356] ip-172-31-94-187/ERROR/stderr: File "src/gevent/event.py", line 409, in gevent._event.AsyncResult.get
[2018-07-06 16:41:21,356] ip-172-31-94-187/ERROR/stderr: File "src/gevent/event.py", line 399, in gevent._event.AsyncResult.get
[2018-07-06 16:41:21,356] ip-172-31-94-187/ERROR/stderr: File "src/gevent/event.py", line 379, in gevent._event.AsyncResult._raise_exception
[2018-07-06 16:41:21,356] ip-172-31-94-187/ERROR/stderr: File "/home/ubuntu/.local/lib/python2.7/site-packages/gevent/threadpool.py", line 281, in _worker

```
note :- the master and the slave the same pip freeze value witch is as the following
```
pip freeze
certifi==2018.4.16
chardet==3.0.4
click==6.7
Flask==1.0.2
gevent==1.3.2.post0
greenlet==0.4.13
idna==2.6
itsdangerous==0.24
Jinja2==2.10
locust==0.8
MarkupSafe==1.0
msgpack-python==0.5.6
paho-mqtt==1.1
pyzmq==17.0.0
requests==2.18.4
six==1.11.0
urllib3==1.22
Werkzeug==0.14.1

```

**Comment by cgoldberg** [comment]
> try to use it in distribution mode it output only two users per slave

how are you starting locust on master and slave?

**Comment by MarwaAbed** [comment]
for Master I use
` locust -f locustfile.py --master --host=HOST_IP:PORT`        with out typing http:// because it is mqtt protocol
for slave I use 
`locust -f locustfile.py --slave --master-host=master-ip`

**Comment by aldenpeterson-wf** [comment]
Do you experience the same issue on a stable build of gevent?

**Comment by cyberw** [comment]
Hi @MarwaAbed ! Sorry for the lack of response. Hopefully this has been solved.
