### ISSUE TITLE
Execute `locust` command,  "ImportError: DLL load failed"

### ISSUE THREAD

**Issue by yuji38kwmt** [locustio/locust#928]
### Description of issue / feature request

I was trying to install locust on windows10, but I got error when executing `locust` command.

```
> locust
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\locust-script.py", line 5, in <module>
    from locust.main import main
  File "C:\ProgramData\Anaconda3\lib\site-packages\locust\main.py", line 14, in <module>
    from . import events, runners, web
  File "C:\ProgramData\Anaconda3\lib\site-packages\locust\runners.py", line 18, in <module>
    from .rpc import Message, rpc
  File "C:\ProgramData\Anaconda3\lib\site-packages\locust\rpc\__init__.py", line 1, in <module>
    from . import zmqrpc as rpc
  File "C:\ProgramData\Anaconda3\lib\site-packages\locust\rpc\zmqrpc.py", line 1, in <module>
    import zmq.green as zmq
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: 指定されたモジュールが見つかりません。
```

### Environment settings (for bug reports)

- OS: Windows10
- Python version: 3.7.0
- Locust version: 0.8
- Locustio version: 0.9
- conda version: 4.5.11

### Addition 

`locust` command succeeded on python 3.6.6.

**Comment by cyberw** [comment]
Cant reproduce.
