### ISSUE TITLE
Time limit reached,but test does not stop,throw GreenletExit exception

### ISSUE THREAD

**Issue by ttflight** [locustio/locust#953]
### Description of issue / feature request

Hello All,
I've faced with a issue of new locust version 0.9.0
**Test does not stop when time limit reached，and throw GreenletExit exception**

The test command is as follows:
**locust -f mylocustfile.py --no-web -c 10 -r 10 -t 10s**

Who can help me solve this problem? Thanks very much!

### Expected behavior

[2019-01-28 11:39:41,407] centos7/INFO/locust.main: Time limit reached. Stopping Locust.
[2019-01-28 11:39:41,408] centos7/INFO/locust.main: Shutting down (exit code 0), bye.
[2019-01-28 11:39:41,408] centos7/INFO/locust.main: Cleaning up runner...

### Actual behavior

[2019-01-28 11:39:41,407] centos7/INFO/locust.main: Time limit reached. Stopping Locust.
[2019-01-28 11:39:41,408] centos7/INFO/locust.main: Shutting down (exit code 0), bye.
[2019-01-28 11:39:41,408] centos7/INFO/locust.main: Cleaning up runner...
[2019-01-28 11:39:41,408] centos7/ERROR/stderr: Traceback (most recent call last):
[2019-01-28 11:39:41,408] centos7/ERROR/stderr: File "/home/locust/mylocustfile.py", line 187, in uploadFileByWebsocket
[2019-01-28 11:39:41,408] centos7/ERROR/stderr: File "/usr/lib/python2.7/site-packages/websocket_client-0.41.0-py2.7.egg/websocket/_core.py", line 293, in recv
[2019-01-28 11:39:41,409] centos7/ERROR/stderr: opcode, data = self.recv_data()
[2019-01-28 11:39:41,409] centos7/ERROR/stderr: File "/usr/lib/python2.7/site-packages/websocket_client-0.41.0-py2.7.egg/websocket/_core.py", line 310, in recv_data
[2019-01-28 11:39:41,409] centos7/ERROR/stderr: opcode, frame = self.recv_data_frame(control_frame)
[2019-01-28 11:39:41,409] centos7/ERROR/stderr: File "/usr/lib/python2.7/site-packages/websocket_client-0.41.0-py2.7.egg/websocket/_core.py", line 323, in recv_data_frame
[2019-01-28 11:39:41,409] centos7/ERROR/stderr: frame = self.recv_frame()
[2019-01-28 11:39:41,409] centos7/ERROR/stderr: File "/usr/lib/python2.7/site-packages/websocket_client-0.41.0-py2.7.egg/websocket/_core.py", line 357, in recv_frame
[2019-01-28 11:39:41,409] centos7/ERROR/stderr: return self.frame_buffer.recv_frame()
[2019-01-28 11:39:41,409] centos7/ERROR/stderr: File "/usr/lib/python2.7/site-packages/websocket_client-0.41.0-py2.7.egg/websocket/_abnf.py", line 336, in recv_frame
[2019-01-28 11:39:41,410] centos7/ERROR/stderr: self.recv_header()
[2019-01-28 11:39:41,410] centos7/ERROR/stderr: File "/usr/lib/python2.7/site-packages/websocket_client-0.41.0-py2.7.egg/websocket/_abnf.py", line 286, in recv_header
[2019-01-28 11:39:41,410] centos7/ERROR/stderr: header = self.recv_strict(2)
[2019-01-28 11:39:41,410] centos7/ERROR/stderr: File "/usr/lib/python2.7/site-packages/websocket_client-0.41.0-py2.7.egg/websocket/_abnf.py", line 371, in recv_strict
[2019-01-28 11:39:41,410] centos7/ERROR/stderr: bytes_ = self.recv(min(16384, shortage))
[2019-01-28 11:39:41,410] centos7/ERROR/stderr: File "/usr/lib/python2.7/site-packages/websocket_client-0.41.0-py2.7.egg/websocket/_core.py", line 427, in _recv
[2019-01-28 11:39:41,410] centos7/ERROR/stderr: return recv(self.sock, bufsize)
[2019-01-28 11:39:41,410] centos7/ERROR/stderr: File "/usr/lib/python2.7/site-packages/websocket_client-0.41.0-py2.7.egg/websocket/_socket.py", line 80, in recv
[2019-01-28 11:39:41,410] centos7/ERROR/stderr: bytes_ = sock.recv(bufsize)
[2019-01-28 11:39:41,411] centos7/ERROR/stderr: File "/usr/lib64/python2.7/site-packages/gevent/_socket2.py", line 295, in recv
[2019-01-28 11:39:41,427] centos7/ERROR/stderr: self._wait(self._read_event)
[2019-01-28 11:39:41,427] centos7/ERROR/stderr: File "src/gevent/_hub_primitives.py", line 265, in gevent.__hub_primitives.wait_on_socket
[2019-01-28 11:39:41,428] centos7/ERROR/stderr: File "src/gevent/_hub_primitives.py", line 266, in gevent.__hub_primitives.wait_on_socket
[2019-01-28 11:39:41,428] centos7/ERROR/stderr: File "src/gevent/_hub_primitives.py", line 261, in gevent.__hub_primitives._primitive_wait
[2019-01-28 11:39:41,428] centos7/ERROR/stderr: File "src/gevent/_hub_primitives.py", line 262, in gevent.__hub_primitives._primitive_wait
[2019-01-28 11:39:41,428] centos7/ERROR/stderr: File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
[2019-01-28 11:39:41,429] centos7/ERROR/stderr: File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
[2019-01-28 11:39:41,429] centos7/ERROR/stderr: File "src/gevent/_hub_primitives.py", line 55, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
[2019-01-28 11:39:41,429] centos7/ERROR/stderr: File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
[2019-01-28 11:39:41,429] centos7/ERROR/stderr: File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
[2019-01-28 11:39:41,429] centos7/ERROR/stderr: File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
[2019-01-28 11:39:41,430] centos7/ERROR/stderr: File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
[2019-01-28 11:39:41,430] centos7/ERROR/stderr: File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
[2019-01-28 11:39:41,430] centos7/ERROR/stderr: GreenletExit

### Environment settings (for bug reports)

- OS: CentOS Linux release 7.3.1611
- Python version: 2.7.5
- Locust version: 0.9.0

### Steps to reproduce (for bug reports)

Please see Description of issue.

**Comment by cgoldberg** [comment]
looks like this is coming from your file: `/home/locust/mylocustfile.py`, line 187, in uploadFileByWebsocket

**Comment by aldenpeterson-wf** [comment]
This cannot be reproduced with the information you've provided.
