### ISSUE TITLE
locust.runners.MasterLocustRunner failed with ExtraData

### ISSUE THREAD

**Issue by Zeloslaw** [locustio/locust#956]
### Description of issue / feature request

I can not run the locust (master)

### Expected behavior

I should be able to run the locust (master)

### Actual behavior

`D:\Projects\locust-performance-test>locust -f locust-master.py --master --master-bind-host=127.0.0.1 --master-bind-port=5557

[2019-02-05 10:47:39,437] lpp/INFO/locust.main: Starting web monitor at *:8089
[2019-02-05 10:47:39,452] lpp/INFO/locust.main: Starting Locust 0.9.0
[2019-02-05 10:47:45,651] lpp/ERROR/stderr: Traceback (most recent call last):
[2019-02-05 10:47:45,652] lpp/ERROR/stderr:
[2019-02-05 10:47:45,653] lpp/ERROR/stderr: File "src\gevent\greenlet.py", line 766, in gevent._greenlet.Greenlet.run
[2019-02-05 10:47:45,653] lpp/ERROR/stderr:
[2019-02-05 10:47:45,654] lpp/ERROR/stderr: File "d:\sdks\python-3.6.8\lib\site-packages\locust\runners.py", line 318, in client_listener
    msg = self.server.recv()
[2019-02-05 10:47:45,654] lpp/ERROR/stderr:
[2019-02-05 10:47:45,654] lpp/ERROR/stderr: File "d:\sdks\python-3.6.8\lib\site-packages\locust\rpc\zmqrpc.py", line 13, in recv
    return Message.unserialize(data)
[2019-02-05 10:47:45,655] lpp/ERROR/stderr:
[2019-02-05 10:47:45,655] lpp/ERROR/stderr: File "d:\sdks\python-3.6.8\lib\site-packages\locust\rpc\protocol.py", line 15, in unserialize
    msg = cls(*msgpack.loads(data, raw=False))
[2019-02-05 10:47:45,655] lpp/ERROR/stderr:
[2019-02-05 10:47:45,656] lpp/ERROR/stderr: File "msgpack\_unpacker.pyx", line 209, in msgpack._cmsgpack.unpackb
[2019-02-05 10:47:45,656] lpp/ERROR/stderr:
[2019-02-05 10:47:45,656] lpp/ERROR/stderr: msgpack.exceptions.ExtraData: unpack(b) received extra data.
[2019-02-05 10:47:45,657] lpp/ERROR/stderr:
[2019-02-05 10:47:45,657] lpp/ERROR/stderr: 2019-02-05T09:47:45Z
[2019-02-05 10:47:45,657] lpp/ERROR/stderr:
[2019-02-05 10:47:45,657] lpp/ERROR/stderr: <Greenlet at 0x1772813e048: <bound method MasterLocustRunner.client_listener of <locust.runners.MasterLocustRunner object at 0x000001772811FEF0>>> failed with ExtraData`

### Environment settings (for bug reports)

- OS: Windows 10
- Python version: 3.6.8-amd64
- Locust version: 0.9.0

### Steps to reproduce (for bug reports)

- Install python 3.6.8 on Windows 10 (Windows x86-64 executable installer)
- Create file locust-master.py
- Run command: pip install locustio
- Run command: locust -f locust-master.py --master --master-bind-host=127.0.0.1 --master-bind-port=5557
- Go to webpage on browser: http://127.0.0.1:5557/

**Comment by cgoldberg** [comment]
> Go to webpage on browser: http://127.0.0.1:5557/

port 5557 is used for slaves connecting to the master.  try opening a browser using port 8089 instead.
